### ISSUE TITLE
Youtube Adblock

### ISSUE THREAD

**Issue by georgysaumen** [AdguardTeam/HostlistsRegistry#105]
Hi,

Can u add this blocklist to ur blocklist list in Adguard DNS dashboard page ?

https://raw.githubusercontent.com/kboghdady/youTube_ads_4_pi-hole/master/youtubelist.txt

Thanks

**Comment by ameshkov** [comment]
In our experience all these lists appear to be very problematic:

1. Youtube ads are rarely blocked at all.
2. Legit videos are very often getting blocked.

In addition to that, this list does not receive updates for the last 2 months. These lists should be updated on hourly basis to at least have a chance (there's still little chance though).
