### ISSUE TITLE
Add Inversion DNSBL

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/HostlistsRegistry#110]
https://github.com/elliotwutingfeng/Inversion-DNSBL-Blocklists

**Comment by ameshkov** [comment]
Isn't this basically Google Safebrowsing API scraping?

**Comment by Sergey-Lyapin** [comment]
@ameshkov 
`These blocklists are automatically generated by scanning various public URL sources using the Safe Browsing API from [Google](https://developers.google.com/safe-browsing).`

So we should not add it?

**Comment by ameshkov** [comment]
Thank you!
