### ISSUE TITLE
Add 1Hosts Pro and Xtra.

### ISSUE THREAD

**Issue by HoVeRzzz** [AdguardTeam/HostlistsRegistry#111]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

1Hosts Pro and Xtra

### Blocklist category

Ad blocking, Trackers blocking, Malware&phishing blocking, Other

### Homepage

https://github.com/badmojr/1Hosts

### Explanation

I think this blocklist should be included, since ur servers lack the ability to add more "extreme" blacklists. And I think this is one of the best repos for that purpose.

**Comment by ameshkov** [comment]
Duplicates #50, let's continue there please
