### ISSUE TITLE
Blocklist suggestion | Facebook List

### ISSUE THREAD

**Issue by Piber0** [AdguardTeam/HostlistsRegistry#114]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

The Block List Project - Facebook List (adguard)

### Blocklist category

Other

### Homepage

https://github.com/blocklistproject/Lists

### Explanation

Block Facebook and Facebook related / owned services.

Download link : https://blocklistproject.github.io/Lists/adguard/facebook-ags.txt

**Comment by hagezi** [comment]
@Piber0 Implemented by the ability to block entire services in AdGuard Home / AdGuardDNS.

![grafik](https://user-images.githubusercontent.com/104343908/206465969-5eaa6655-146e-4ec6-99ea-0f1ddf116d94.png)

**Comment by ameshkov** [comment]
Duplicates #82

**Comment by hagezi** [comment]
In the server settings under Parental Control.
