### ISSUE TITLE
Add EasyList and EasyPrivacy

### ISSUE THREAD

**Issue by Yanashima98** [AdguardTeam/HostlistsRegistry#118]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

EasyList, EasyPrivacy,

### Blocklist category

Ad blocking, Trackers blocking

### Homepage

https://easylist.to/

### Explanation

EasyList:
https://v.firebog.net/hosts/Easylist.txt

EasyPrivacy:
https://v.firebog.net/hosts/Easyprivacy.txt

**Comment by T145** [comment]
These are already included in the [Adguard DNS list](https://github.com/AdguardTeam/AdGuardSDNSFilter#dns-filter-structure)

**Comment by ameshkov** [comment]
These lists are not supposed to be used on the DNS level.
