### ISSUE TITLE
Please add OSINT active threat intelligence list

### ISSUE THREAD

**Issue by gorillap** [AdguardTeam/HostlistsRegistry#119]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

OSINT Threat Intel list

### Blocklist category

Malware&phishing blocking

### Homepage

https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt

### Explanation

List of recently reported harmful URL's. Currently working with Adguard Home.

**Comment by Alex-302** [comment]
Too small.
