### ISSUE TITLE
My current blocklist-setup

### ISSUE THREAD

**Issue by iJorgen** [AdguardTeam/HostlistsRegistry#12]
My current blocklist setup with another service that gives me great privacy with minimal white-listing. Would be nice to try the same setup here...

- 1Hosts (Pro)
- Lightswitch05 - Ads & Tracking
- notracking
- oisd (full)
- AdGuard DNS filter
- Fanboy's Annoyance List
- Steven Black

**Comment by DandelionSprout** [comment]
Can be done by adding custom list URLs in AdGuard Home's list settings, or AdGuard for Windows/Android's DNS settings. To add the above ones (minus AdGuard DNS Filter), use the following URLs:
* https://raw.githubusercontent.com/badmojr/1Hosts/master/Pro/adblock.txt
* https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt
* https://raw.githubusercontent.com/notracking/hosts-blocklists/master/adblock/adblock.txt
* https://dbl.oisd.nl/
* https://easylist-downloads.adblockplus.org/fanboy-annoyance.txt
* https://raw.githubusercontent.com/StevenBlack/hosts/master/data/StevenBlack/hosts

**Comment by ameshkov** [comment]
* 1Hosts -- discussed here: #50 
* Lightswitch05 -- rejected #27 
* notracking -- rejected, not maintained
* oisd -- added
* Fanboy's Annoyance List -- rejected, not a DNS list
* #43 -- added
