### ISSUE TITLE
Add this blocklist please

### ISSUE THREAD

**Issue by YameYukana** [AdguardTeam/HostlistsRegistry#120]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

HaGeZi's DNS Blocklist

### Blocklist category

Ad blocking, Trackers blocking, Malware&phishing blocking, Other

### Homepage

https://github.com/hagezi/dns-blocklists

### Explanation
add the pro, pro++ and ultimate version?
Its like oisd but better maybe?

An all in one DNS blocklist in various versions (light, normal, pro, pro++ and ultimate). It can be used as a stand alone blocklist. For every region. Blocks ads, affiliate, tracking, metrics, telemetry, fake, phishing, malware, scam, coins and other "crap". Based on [various blocklists].

**Comment by marcoclg19** [comment]
#101

**Comment by Sergey-Lyapin** [comment]
HaGeZi Personal Black & White was already added:
https://github.com/AdguardTeam/HostlistsRegistry/pull/101
https://github.com/AdguardTeam/HostlistsRegistry/pull/103
