### ISSUE TITLE
Add Dandelion Sprout's AdGuard Home Compilation List

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/HostlistsRegistry#121]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

Dandelion Sprout's AdGuard Home Compilation List

### Blocklist category

Ad blocking, Other

### Homepage

https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AdGuard%20Home%20Compilation%20List/AdGuardHomeCompilationList.txt

### Explanation

It's a conversion of many very-high-profile filterlists into the AdGuard Home syntax, and the conversion process is done much better than the one used by AdGuard DNS Filter, including support for wildcarding and for entries that are not hosted in `adservers.txt` files.

Currently, the lists included in the conversion are:
* EasyList
* AdGuard Base Filter
* uBlock Filters
* uBlock Filters - Badware Risks
* ABP Filters (Blocking-rules only)
* Adblock Warning Removal List
* AdGuard French Filter (incl. Liste FR)
* EasyList Germany
* EasyList Spanish
* RU AdList
* Liste AR
* I Don't Care About Cookies (Give me a headsup if it's preferable that Compilation List shouldn't include that one)

I've done 10 updates to the list in the 2 weeks before I created this issue report. While the list was initially designed back in 2020 as more or less a competitor to AdGuard DNS Filter, I think it'd be perfectly possible and feasible to use both at the same time, especially given that most of their source lists/files differ from one another.

**Comment by Alex-302** [comment]
> ! *** easylist:easylist/easylist_general_block_popup.txt ***
> ! *** easylist:easylist/easylist_general_block.txt ***

are they required in DNS filter?

**Comment by DandelionSprout** [comment]
Not really; I just presumed people would want to know the original GitHub repo files the entries came from.

**Comment by Alex-302** [comment]
I mean the rules in that sections - they are not as domains and cannot be used for DNS filtering.

**Comment by DandelionSprout** [comment]
They can be used. It can easily be tested by adding a random entry from those sections, for instance `-popexit.` to My Filters, then trying to visit `exampletext-popexit.org` and see that it gets blocked.

**Comment by Alex-302** [comment]
ok then

**Comment by Alex-302** [comment]
These filters are included in AdGuard DNS filter:

```
EasyList
AdGuard Base Filter
AdGuard French Filter (incl. Liste FR)
EasyList Germany
```

Usually we prefer to add original lists.
