### ISSUE TITLE
Custom a domain for this github page | 为这个项目的GitHub Page自定义一个域名

### ISSUE THREAD

**Issue by hacamer** [AdguardTeam/HostlistsRegistry#124]
As the title says, create your own domain name for the GitHub Page of this project
Due to the unique nature of the network in mainland China, some regional carriers may block access to `github.io`.
Customizing a domain name will solve this problem
For example: `adguardteam.github.io` => `[Custom Domain]` (just an example here)
![](https://user-images.githubusercontent.com/73057402/209644309-b8de19b2-5cb6-4971-ad1d-33e92923620c.png)

Good luck!

---

Original Text (Simplified Chinese)：

>如题所说，为这个项目的GitHub Page自定一个域名
>由于中国大陆网络的特殊性 某些地区的运营商会阻断对 `github.io` 的连接
>自定义一个域名将能解决这个问题
>如：`adguardteam.github.io` => `[自定义域名]` （这里只是举例）
>祝好运

**Comment by hacamer** [comment]
For example : `https://adguardteam.github.io/HostlistsRegistry/filters/general/filter_1_DnsFilter/filter.txt` => `https://[custom domain]/HostlistsRegistry/filters/general/filter_1_DnsFilter/filter.txt`

>例子 : `https://adguardteam.github.io/HostlistsRegistry/filters/general/filter_1_DnsFilter/filter.txt` => `https://[自定义域名]/HostlistsRegistry/filters/general/filter_1_DnsFilter/filter.txt`

**Comment by Sergey-Lyapin** [comment]
@ameshkov Please take a look

**Comment by Alex-302** [comment]
If github.io is blocked, I think they block also all subdomains.
