### ISSUE TITLE
Amazon.com.be not filtered

### ISSUE THREAD

**Issue by BirdInFire** [AdguardTeam/HostlistsRegistry#127]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, Other (please mention the version in the description)

### CPU architecture

AMD64

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

0.107.17

#### What did you do?
Checked if the new amazon domain for belgium (amazon.com.be)

#### Expected result
Having an error page

#### Actual result
The page loaded (minus some css hosted on amazon.com)

#### Screenshots (if applicable)
Since it's a belgian version it's in french.

![image](https://user-images.githubusercontent.com/42673166/199635755-fab6feff-5e15-41e4-9052-c15058960701.png)

#### Additional information
To fix this you only have to add : ||amazon.com.be^ to the "amazon" under services blocklist.

**Comment by sandervankasteel** [comment]
Since this is merged now, this issue can be closed right @ameshkov / @IldarKamalov ?

**Comment by ameshkov** [comment]
Yep, thanks
