### ISSUE TITLE
Add AdRules(For DNS)

### ISSUE THREAD

**Issue by hacamer** [AdguardTeam/HostlistsRegistry#13]
Describe: DNS filter based on China zone
Auto Mergo New Rules From Upstream Website

Update time: eight hours

Link: https://raw.githubusercontent.com/Cats-Team/AdRules/main/dns.txt

Homepages:https://github.com/Cats-Team/AdRules

One caveat: developers will often debug this rule so it may be unstable

**Comment by hacamer** [comment]
If AGHOME or AG DNS BETA supports more rules, it may be better to use AdRules(For Adblock) than AdRules(For DNS), but I still recommend using the two filters together.

AdRules(For Adblock) Link:https://raw.githubusercontent.com/Cats-Team/AdRules/main/adblock.txt

**Comment by ameshkov** [comment]
在你的repo写着“来自上游网站”。请告诉我那些上游网站是什么网站？

**Comment by hacamer** [comment]
> 谢谢，看到了。来我们考虑，正常我们把“合并规则”这种列表不会加，但有一些流行的列表很多人要求，我们可能复议。

是的，合并类的规则似乎有很多人需求，例如较为著名的anti-AD，这个就是合并类规则。建议建立一个第三方列表，用于存放此类规则，并注明此类规则稳定性与过滤效果不受保障
