### ISSUE TITLE
Additional application for tofu filter

### ISSUE THREAD

**Issue by kusakakka** [AdguardTeam/HostlistsRegistry#137]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

JPN TOFU Filter(豆腐フィルタ)

### Blocklist category

Ad blocking

### Homepage

https://github.com/tofukko/filter

### Explanation

This "Tofu Filter" excludes not only the advertisement data but also the inline script elements of the advertisement elements on various SNS and streaming sites in Japan, so it corresponds to the advertisement elements that the default list of AdGuardDNS cannot handle. It is possible, but only the built-in list can be applied in the cooperation mode with AdGuardVPN, so please adopt this excellent list.

https://github.com/tofukko/filter/blob/master/Adblock_Plus_list.txt

**Comment by Alex-302** [comment]
This filter has Adblock syntax, not hosts.

**Comment by ameshkov** [comment]
@Alex-302 why is that a problem?

**Comment by ameshkov** [comment]
Ah, my bad. The filter is created for traditional browser-based blockers, it's full of cosmetic lists.
