### ISSUE TITLE
Icon guidelines

### ISSUE THREAD

**Issue by sandervankasteel** [AdguardTeam/HostlistsRegistry#140]
Hi,

Over the last while, I've been doing some pull requests for adding services so that they can be blocked and I definitely wanna do more of those. But one of the things, I noticed with my PR's is that I am primarily getting feedback on the icons, I use.

Are there any guidelines / rules with regards to the icons? So I know what the requirements are for the icons.

**Comment by ameshkov** [comment]
Hi!

Briefly, the guidelines are:

1. Square shape
2. The icon should be black&white
3. As small as possible

**Comment by sandervankasteel** [comment]
Perfect :) Thanks for your answer. 

One last question, what in the case when the logo of the service isn't square ? One of the logo's that come to mind is the logo of Amazon Prime Video.

**Comment by ainar-g** [comment]
@ameshkov, `fill="currentColor"` is also important for themes to work properly.  See AdguardTeam/AdGuardHome#5433.

**Comment by sandervankasteel** [comment]
> @ameshkov, `fill="currentColor"` is also important for themes to work properly. See [AdguardTeam/AdGuardHome#5433](https://github.com/AdguardTeam/AdGuardHome/issues/5433).

That's definitely good to know. Especially, because I am the person that initially made the PR to include League of Legends as a blockable service.
