### ISSUE TITLE
Please can you consider adding my personal blocklist?

### ISSUE THREAD

**Issue by Eow2022yia** [AdguardTeam/HostlistsRegistry#147]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

Jonathan’s Personal Blocklist

### Blocklist category

Ad blocking, Trackers blocking, Malware&phishing blocking

### Homepage

pastebin.com/BpNm2CEn

### Explanation

Hi,

I really hope you can consider adding my list, it is mainly beneficial for blocking iOS trackers and ads and features many essential domains other maintainers won’t cover.

Thank you.

**Comment by ameshkov** [comment]
Unfortunately, the space for blocklists is limited and we don't add personal blocklists here.

Please check out the inclusion criteria in the repo description.
