### ISSUE TITLE
Can I add a internall filter for CHN

### ISSUE THREAD

**Issue by Natsuki-Kaede** [AdguardTeam/HostlistsRegistry#149]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [x] I want to request a feature or enhancement and not ask a question

### Description

A CHN region optimized rule for AdGuardHome 
https://github.com/Natsuki-Kaede/Sophie-List

**Comment by Sergey-Lyapin** [comment]
Hello @Natsuki-Kaede

It seems your filter does not pass the popularity criterion.

- The blocklist should be relatively popular, meaning:
  - if there is a repository on GitHub, the number of stars should be at least 50.
  - if there is no repository on GitHub, the number of reported issues and discussions should be at least 10 per month.
  - the blocklist should be actively supported for at least 6 months.
  
https://github.com/AdguardTeam/HostlistsRegistry#what-blocklists
