### ISSUE TITLE
Add AdAway Blocking Hosts File for Japan - Block List

### ISSUE THREAD

**Issue by zhiyuan-lin** [AdguardTeam/HostlistsRegistry#15]
* List URL: https://logroid.github.io/adaway-hosts/hosts.txt
* Support URL: https://github.com/logroid/adaway-hosts/issues
Reason for inclusion: "If the blocklist is popular in a specific region and there are no alternatives to it, then it can be added as is even if it does not satisfy requirements above." - This list is popular hostname based block list for Japanese language website, which is currently missing from AdGuard's selection.

**Comment by ameshkov** [comment]
@Yuki2718 could you please help me with this one? Trying to assess if the list should be added or not.

It's hard to say how good it is considering the repo is not too active.

**Comment by Yuki2718** [comment]
IDK the criteria for adding a new list. I think it's active enough for limited-purpose (for Japanese Android user) hosts file. The only problem I see is many entries (apparently those taken from JPF) lack subdomain despite it's hosts file (e.g. `127.0.0.1 waqool.com` doesn't make sense as in-the-wild domain is `js.waqool.com`), but it won't matter to AG.

**Comment by Yuki2718** [comment]
Another problem is it blocks some whole websites e.g. `6ms.biz` is a NSFW website and can be blocked only if third-party: https://github.com/AdguardTeam/AdguardFilters/commit/f2c4c4ceb9471b63ba01c1d535d31a3dd2348f7b .But such entries won't be too many and not a major problem (unlike `t.co`). Overall the list is well-maintained and looks not bad.

**Comment by ameshkov** [comment]
Still cannot decide about this one. Even though the list looks good, there're almost no issues in the repo as if it's a personal list.

Hello @logroid, could you please comment here? We were requested to add your blocklist to the list of available blocklists in AdGuard Home and AdGuard DNS. Including it may attract more attention to the list, more users -> more reports. If it would bother you, please let us know.

**Comment by Sergey-Lyapin** [comment]
@logroid
