### ISSUE TITLE
HaGeZi's Lists - Normal, Pro, Pro++

### ISSUE THREAD

**Issue by tilty79** [AdguardTeam/HostlistsRegistry#153]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

HaGeZi - Normal, Pro, Pro++

### Blocklist category

Other

### Homepage

https://github.com/hagezi/dns-blocklists

### Explanation

I've read about how great these lists are on multiple threads and it is actively updated to remove false positives.

**Comment by jslawler** [comment]
#101

**Comment by tilty79** [comment]
Sorry all, I was only looking at open issues since these aren't current blocklist choices. In reading #101, as a user who would rather have one solid list than adding a bunch of smaller lists that may overlap, I think these lists would be a great addition and I notice that other DNS services have added these because of their utility. Closing this as to avoid duplication.
