### ISSUE TITLE
Add EasyList Germany

### ISSUE THREAD

**Issue by Crstn1985** [AdguardTeam/HostlistsRegistry#154]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

EasyList Germany

### Blocklist category

Ad blocking

### Homepage

https://easylist.to/easylistgermany/easylistgermany.txt

### Explanation

removes adverts on German language websites

**Comment by Sergey-Lyapin** [comment]
Hello @Crstn1985

The blocklist should be oriented towards DNS-level content blockers. There is a different [repo](https://github.com/AdguardTeam/FiltersRegistry) for browser content blockers.
