### ISSUE TITLE
Add "NoTrack Tracker Blocklist"

### ISSUE THREAD

**Issue by Xeunyx-Cypher** [AdguardTeam/HostlistsRegistry#160]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

NoTrack Tracker Blocklist

### Blocklist category

Ad blocking, Trackers blocking, Malware&phishing blocking

### Homepage

https://gitlab.com/quidsup/notrack-blocklists

### Explanation

It's a very good Blocklist I've used previously while using Nextdns. If this list seems a bit aggressive then please add a tag next to it warning the user before they add them manually. But please add it to the manage Blocklist page.

https://gitlab.com/quidsup/notrack-blocklists

**Comment by hagezi** [comment]
See: https://github.com/AdguardTeam/HostlistsRegistry/issues/56

**Comment by Sergey-Lyapin** [comment]
duplicate
https://github.com/AdguardTeam/HostlistsRegistry/issues/56
