### ISSUE TITLE
Discussion about the Amazon service

### ISSUE THREAD

**Issue by sandervankasteel** [AdguardTeam/HostlistsRegistry#163]
I wanted to have a little discussion about the Amazon service it's currently defined in the `services.json`. 

At the moment the domains for the regular Amazon (ie, the shopping website) and Amazon Prime Video are lumped into the "Amazon" service. See lines 97 through 99 in the `service.json` ([direct link](https://github.com/AdguardTeam/HostlistsRegistry/blob/main/assets/services.json#L97-L99)).

Other then that, I found that a lot of other Amazon related services like boxofficemojo.com and their AWS Educate website (to name a few) are also blocked in that same service.

The main question is, is it desirable to block all those adjacent services in that particular service ?

**Comment by ameshkov** [comment]
Once we start splitting those into smaller services, we'll have to do the same for Microsoft and Google.

There are dozens of services provided by each and I am afraid there will be just too many.
