### ISSUE TITLE
oisd extra

### ISSUE THREAD

**Issue by tychoregter** [AdguardTeam/HostlistsRegistry#165]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

oisd extra

### Blocklist category

Ad blocking, Trackers blocking, Malware&phishing blocking

### Homepage

https://oisd.nl/downloadsXtra

### Explanation

I am not 100% sure if this blocklist perfectly satisfies the requirements (the updates one for example). But, since oisd is included in AdGuard DNS I think the oisd extra blocklist would be a great addition for those who like oisd, but just want that tiny bit of extra blocking power. It would be more of an extension to the already included oisd filter.

**Comment by jslawler** [comment]
This blocklist no longer exists and has been replaced with oisd full and oisd small.
