### ISSUE TITLE
Add your own/custom list

### ISSUE THREAD

**Issue by fpellicciotti** [AdguardTeam/HostlistsRegistry#17]
It would be nice to have the ability to add your own block lists, like what we have in AdGuard Home.

**Comment by klisza1993** [comment]
http://hole.cert.pl/domains/domains_hosts.txt

**Comment by QuentinHsu** [comment]
I strongly endorse this recommendation!

**Comment by checked-wobbles-0p** [comment]
Agreed! Be nice to have an “advance user” option to manually add block list sources.

**Comment by badmojr** [comment]
Expensive! -1

**Comment by ameshkov** [comment]
It should be filed to https://github.com/AdguardTeam/AdGuardDNS repo as a feature request.

Generally, this is indeed very expensive for a mass service to allow adding any list.
We were thinking about increasing the user rules limit for Team / Enterprise plan, I doubt we'll manage to do that for all users.
