### ISSUE TITLE
Slickdeals and Rakuten Whitelist

### ISSUE THREAD

**Issue by DevEstacion** [AdguardTeam/HostlistsRegistry#171]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

Slickdeals and Rakuten Whitelist

### Blocklist category

Other

### Homepage

https://help.slickdeals.net/hc/en-us/articles/1260800863609-How-to-Guarantee-Cashback-is-Tracked-when-Running-Ad-Blockers

### Explanation

Slickdeals
https://help.slickdeals.net/hc/en-us/articles/1260800863609-How-to-Guarantee-Cashback-is-Tracked-when-Running-Ad-Blockers

Rakuten
https://www.rakuten.com/whitelist/ebates-cash-back-shopping.txt

**Comment by Sergey-Lyapin** [comment]
Thanks for your suggestion but these lists do not seem to meet the conditions:

```
- The blocklist should have a place for receiving user complaints and holding discussions, such as a repository on github.com, or a public website/forum.
- The blocklist should be relatively popular, meaning:
  - if there is a repository on GitHub, the number of stars should be at least 50.
  - if there is no repository on GitHub, the number of reported issues and discussions should be at least 10 per month.
  - the blocklist should be actively supported for at least 6 months.
- The blocklist should be regularly updated with at least 10 updates per month.
```
