### ISSUE TITLE
Please add Finnish Easylist Addition 

### ISSUE THREAD

**Issue by Raitsa** [AdguardTeam/HostlistsRegistry#184]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

Finnish Easylist Addition

### Blocklist category

Ad blocking, Trackers blocking

### Homepage

https://github.com/finnish-easylist-addition/finnish-easylist-addition

### Explanation

This list is quite popular in Finland, very useful and multipurposed. Keeps getting updates often. A must.

**Comment by Sergey-Lyapin** [comment]
Hello @Raitsa 

The blocklist should be oriented towards DNS-level content blockers. There is a different [repo](https://github.com/AdguardTeam/FiltersRegistry) for browser content blockers.

And we already have that filter there:
https://github.com/AdguardTeam/FiltersRegistry/tree/master/filters/ThirdParty/filter_233_AdblockListFinland
