### ISSUE TITLE
Add uBlock₀ filters – Badware risks

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/HostlistsRegistry#197]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

uBlock₀ filters – Badware risks

### Blocklist category

Malware&phishing blocking

### Homepage

https://github.com/uBlockOrigin/uAssets

### Explanation

I had to check
> The blocklist is created specifically for DNS-level blockers; 

but no, it's not for DNS; however, the list includes lots of bad domain not found on other available security lists.

**Comment by DandelionSprout** [comment]
Direct link to the list: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/badware.txt

To make list conversion to DNS blockers easier, I would've added support for `$all` as an alias for no $values in https://github.com/AdguardTeam/DnsLibs/tree/master/dnsfilter, but it seems very difficult to write such a fix.

**Comment by ameshkov** [comment]
@DandelionSprout I would generally avoid relaxing DNS rules syntax.

There's no goal to make DNS filtering compatible with browser blockers' lists, on the contrary, I think this may lead to some unexpected results.

DNS filtering is for DNS, `$all` semantically does not make any sense on the DNS level so there's no place for it in the lists that are supposed to be used by DNS blockers.

There is always HostlistsCompiler that may be used for automatic conversion and removing those modifiers: https://github.com/AdguardTeam/HostlistCompiler/tree/master#remove-modifiers

**Comment by Yuki2718** [comment]
Great, can pattern-based and regex rules be removed as well?

**Comment by DandelionSprout** [comment]
I suppose DnsLibs and/or HostlistCompiler could be set up to remove RegExes that'd match the `^/.*\..*\/..*/($|\$)` pattern.

On the other hand, I kinda **love** pattern-based entries of the `-example-entry.` varieties, and am unsure why most AdGuard Home lists skip them entirely.

**Comment by ameshkov** [comment]
@Yuki2718 could you please give us some examples of the rules that should be removed?

**Comment by Yuki2718** [comment]
> could you please give us some examples of the rules that should be removed?

E.g.
```
||newsharecounts.s3-us-west-2.amazonaws.com/nsc.js$script
?adTagId=*&extclickid=$doc
/^https:\/\/[0-9a-z]{3,}\.[-a-z]{10,}\.top\/[a-z]{8}\/\?(?:cid=[0-9a-z]+&)?u=[0-9a-z]+&/$doc,domain=top
```
There are also cosmetic rules such as
```
okashimag.com,tech4yougadgets.com##^script[src^="data:text/javascript;base64,"]
okashimag.com,tech4yougadgets.com##+js(aopr, Notification)
```
So maybe the best is to pick domain rules up by script.

**Comment by ameshkov** [comment]
Cosmetic rules and rules with `script` and `domain` modifier will be discarded automatically.

`?adTagId=*&extclickid=$doc ` -- this one won't be discarded, but on the other hand it won't do any bad.
