### ISSUE TITLE
Blocklist for Arabic 

### ISSUE THREAD

**Issue by bigplayer-ai** [AdguardTeam/HostlistsRegistry#200]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

ara: Liste AR 

### Blocklist category

Ad blocking, Trackers blocking, Malware&phishing blocking, Other

### Homepage

https://forums.lanik.us/viewforum.php?f=98-liste-ar

### Explanation

It block arabic language hosts.

**Comment by Sergey-Lyapin** [comment]
Hello @bigplayer-ai

The blocklist should be oriented towards DNS-level content blockers. There is a different [repo](https://github.com/AdguardTeam/FiltersRegistry) for browser content blockers.

And we already have that filter there:
https://github.com/AdguardTeam/FiltersRegistry/tree/master/filters/ThirdParty/filter_112_ListeAR
