### ISSUE TITLE
Blocklist For ISR

### ISSUE THREAD

**Issue by bigplayer-ai** [AdguardTeam/HostlistsRegistry#201]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

Easylist Hebrew

### Blocklist category

Ad blocking, Trackers blocking, Malware&phishing blocking, Other

### Homepage

https://github.com/easylist/EasyListHebrew

### Explanation

Blocklist for israel country.

**Comment by Sergey-Lyapin** [comment]
Hello @bigplayer-ai

The blocklist should be oriented towards DNS-level content blockers. There is a different [repo](https://github.com/AdguardTeam/FiltersRegistry) for browser content blockers.

And we already have that filter there:
https://github.com/AdguardTeam/FiltersRegistry/tree/master/filters/ThirdParty/filter_108_EasyListHebrew

**Comment by amir16yp** [comment]
> Hello @bigplayer-ai
> 
> The blocklist should be oriented towards DNS-level content blockers. There is a different [repo](https://github.com/AdguardTeam/FiltersRegistry) for browser content blockers.
> 
> And we already have that filter there: https://github.com/AdguardTeam/FiltersRegistry/tree/master/filters/ThirdParty/filter_108_EasyListHebrew

it has a hosts file version
https://raw.githubusercontent.com/easylist/EasyListHebrew/master/hosts.txt
since it has at least 50 stars, and is the only serious blocklist for that region, it should still be added despite not being updated as frequently

**Comment by ameshkov** [comment]
@amir16yp good catch, thank you!

**Comment by Alex-302** [comment]
Or can be inclided to DNS filter
https://github.com/easylist/EasyListHebrew/blob/master/adguard_hosts.txt
