### ISSUE TITLE
Add ShadowWhisperer's Malware list (and possibly few more)

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/HostlistsRegistry#202]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

Malware

### Blocklist category

Malware&phishing blocking

### Homepage

https://github.com/ShadowWhisperer/BlockLists/blob/master/Lists/Malware

### Explanation

The list looks good. GH History shows only recent changes due to compression by the maintainer, but according to the author it's since 2/14/2020. A downside will be it's plain hostname list yet doen't include subdomain (same as ABP style filters). The maintainer also provides other lists which may also be worth addition.

@ShadowWhisperer Hi, I hope you don't mind my bringing of your lists. Do you have any comment on this?

**Comment by Yuki2718** [comment]
Doesn't AGH support [domains-only syntax](https://adguard-dns.io/kb/ja/general/dns-filtering-syntax/#domains-only-syntax)? I'm not intended to burden the maintainer.

**Comment by Sergey-Lyapin** [comment]
@ameshkov 
Should we add lists with adblock-only syntax?
