### ISSUE TITLE
Add List “ADSLJ”

### ISSUE THREAD

**Issue by BugEmpty** [AdguardTeam/HostlistsRegistry#205]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [ ] The blocklist is regularly updated (at least 10 updates per month);
- [ ] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

ADSLJ

### Blocklist category

Ad blocking

### Homepage

https://code.gitlink.org.cn/zzp282/ads/raw/branch/master/ADSLJ.txt

### Explanation

Please add list “ADSLJ”

**Comment by Sergey-Lyapin** [comment]
Hello @BugEmpty

The blocklist should be oriented towards DNS-level content blockers. There is a different [repo](https://github.com/AdguardTeam/FiltersRegistry) for browser content blockers.
