### ISSUE TITLE
Block Youtube ads

### ISSUE THREAD

**Issue by chien2705** [AdguardTeam/HostlistsRegistry#206]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

Youtube and TV ads

### Blocklist category

Ad blocking, Other

### Homepage

youtube.com

### Explanation

Everyone needed

**Comment by Sergey-Lyapin** [comment]
Unfortunately, Youtube ads cannot be removed by DNS filtering. Please use AdGuard adblocker app or extension.
