### ISSUE TITLE
adguard dns beta Blocklist Suggestion

### ISSUE THREAD

**Issue by 88Va2wFDcYd1CT** [AdguardTeam/HostlistsRegistry#21]
List-KR DNS
List-KR(https://github.com/List-KR/List-KR)
is a web filter for websites in Korean language. with AdGuard ad blocker and uBlock Origin.
List-KR DNS filter is Optimized for dns filtering.

https://github.com/List-KR/List-KR/raw/master/filter_DNS.txt

It would be nice if this list could be used in adguard dns beta.

**Comment by ameshkov** [comment]
Duplicate of #11. Please upvote the original issue instead.
