### ISSUE TITLE
DoH/VPN/TOR/Proxy Bypass block list by Hagezi

### ISSUE THREAD

**Issue by 4uto3lend** [AdguardTeam/HostlistsRegistry#213]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

DoH/VPN/TOR/Proxy Bypass

### Blocklist category

Other

### Homepage

https://github.com/hagezi/dns-blocklists#bypass

### Explanation

First good list to block and prevent methods to bypass our DNS. Downsize is that AdGuard names are included. But this isn't a problem for me :)

Many thanks

**Comment by Sergey-Lyapin** [comment]
After discussion in internal chat, we decided not to add this list.

**Comment by Sergey-Lyapin** [comment]
Hello @4uto3lend 
Thanks for the suggestion.
DNS-level blocking is not very suitable for this task, such a list should preferably be applied at another level.

**Comment by ameshkov** [comment]
On a second thought, we could add this list, but we should clearly state in the description that this is not a guarantee, it's easy to bypass DNS level blocking for a VPN software. The simple example is that you can use `https://8.8.8.8/dns-query`.

**Comment by 4uto3lend** [comment]
Indeed. Most things about VPN is just an attempt. Love you guys!
