### ISSUE TITLE
Let ads of duolingo on iphone

### ISSUE THREAD

**Issue by laguill** [AdguardTeam/HostlistsRegistry#219]
Hello,

How can I create a rull To keep having ads when using the app Duolingo on an iPhone.

I don't know the domains to not block.

Thank you for your help

**Comment by Sergey-Lyapin** [comment]
Hello @laguill 
I'm sorry for so late answer.
It seems that unblocking these domains is enough:
```
ad.doubleclick.net
unityads.unity3d.com
adsmoloco.com
pagead2.googlesyndication.com
tpc.googlesyndication.com
googleads.g.doubleclick.net
```
But keep in mind that these domains will be unblocked for all applications.
