### ISSUE TITLE
Disconnect.me (lists to add)

### ISSUE THREAD

**Issue by nightznero** [AdguardTeam/HostlistsRegistry#22]
Helloz,

Hope everyone knows [Disconnect.me](https://disconnect.me)  site and don't have to introduce it. Here's List that they use:

List agaist Ads
[Disconnect.me - ads](https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt) 

List agaist Trackers
[Disconnect.me - trackers](https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt) 

List agaist Malware
[Disconnect.me - malware](https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt)

**Comment by DandelionSprout** [comment]
At 2,735 entries in the anti-malware list, and 2,701 in the anti-ad list, they seem large enough to me to warrant inclusion in AdGuard Home.

**Comment by badmojr** [comment]
` Last-Modified: Sat, 01 Feb 2020 02:37:09 GMT` .

![0uyr](https://user-images.githubusercontent.com/40524316/171978467-f0a28440-a87e-482d-b00a-7c18f8dd1efc.PNG)

**Comment by ameshkov** [comment]
Does not satisfy the following requirements:

> The blocklist should be regularly updated with at least 10 updates per month.

> The blocklist should have a place for receiving user complaints and holding discussions, such as a repository on github.com, or a public website/forum.
