### ISSUE TITLE
推荐一个规则数量多的DNS过滤器

### ISSUE THREAD

**Issue by xiulou23** [AdguardTeam/HostlistsRegistry#220]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

Adblock DNS Filters

### Blocklist category

Ad blocking, Trackers blocking

### Homepage

https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockfilters.txt

### Explanation

因为这是我找到一个一个我自认为的优质过滤器，而且过滤规则众多，8小时更新一次，这个过滤器上游列表中包含许多Adguard中没有的过滤器，如果添加这个过滤器到Adguard过滤器列表中，是一个非常不错的做法，能补充不少Adguard没有的过滤规则。希望你们能尽快审核，如果你们决定加上这个过滤器，希望你们能回复一下我

**Comment by Sergey-Lyapin** [comment]
Hello @xiulou23, I'm sorry for delay.

The blocklist should be oriented towards DNS-level content blockers. There is a different [repo](https://github.com/AdguardTeam/FiltersRegistry) for browser content blockers.
