### ISSUE TITLE
YouTube Ad-Blocking

### ISSUE THREAD

**Issue by crixxy06** [AdguardTeam/HostlistsRegistry#221]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [x] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

YouTube Ad Blocklist

### Blocklist category

Ad blocking

### Homepage

https://github.com/Ewpratten/youtube_ad_blocklist

### Explanation

Hi, I'd like to ask if the YouTube Ad Blocklist can be added to `AdGuard-DNS.io`. It's located here [YouTube Ad Blocklist](https://gh-pages.ewpratten.com/youtube_ad_blocklist/domains.txt), here [YouTube Ad Blocklist GitHub](https://github.com/Ewpratten/youtube_ad_blocklist). This blocklists' purpose is to block all video ads, ad banners, etc on the YouTube website. The repo for the project hasn't been updated in awhile as all currently known domains used for ads are already listed in the blocklist, but is a very popular blocklist, but I'm not sure if it meets all repo requirements such as being supported, as I'm new to GitHub and have very little clue how to find out that information. I'm posting here in response to [YouTube's latest experiment in blocking all the client-level ad blockers from being used to access content on their website](https://www.bleepstatic.com/images/news/u/1109292/2023/YouTube%20ad%20blocker%20warning.jpg). So my approach would be using DNS level ad-blocking to circumvent the issues of using client-level ad blockers on YouTube. Thanks for your consideration in adding the blocklist and I hope to hear back with any questions, comments, or concerns. 

Cheers!
Crixx

**Comment by Sergey-Lyapin** [comment]
Hello @crixxy06, I'm sorry for such a long delay.

Unfortunately we can't add this list because it's archived and hasn't been maintained for a long time.

`all currently known domains used for ads are already listed in the blocklist`
I'm not sure about that, they even didn't merge this pull request for instance.
https://github.com/ewpratten/youtube_ad_blocklist/pull/25
