### ISSUE TITLE
sysctl Blacklist

### ISSUE THREAD

**Issue by hbednar** [AdguardTeam/HostlistsRegistry#222]
### Prerequisites

- [X] The service is not included in the list of [Blocked services](https://github.com/AdguardTeam/HostlistsRegistry/blob/main/assets/services.json).
- [X] This is a popular service and it makes sense to have it blocked;

### Service name

sysctl

### Explanation

Git:
https://github.com/Ultimate-Hosts-Blacklist/cameleon_at_sysctl.org

List:
http://sysctl.org/cameleon/hosts

**Comment by Sergey-Lyapin** [comment]
It is written at the top of the list:
`# Last updated : 2018-03-17`
Looks like this filter hasn't been updated for a long time.

Hello, @smed79
Is it true that this list is not supported since 2018?

**Comment by Sergey-Lyapin** [comment]
Judging by the repository, the rules on the list haven't been updated in a long time and the list doesn't meet the popularity criteria:

```
if there is a repository on GitHub, the number of stars should be at least 50.
if there is no repository on GitHub, the number of reported issues and discussions should be at least 10 per month.
```

**Comment by hagezi** [comment]
@hbednar 
The list itself has not been updated for ages.

https://sysctl.org/cameleon/
![grafik](https://github.com/AdguardTeam/HostlistsRegistry/assets/104343908/3f9176cc-0226-4515-b6b8-f924fcaf3bdc)

Take a look at what has been changed in the listed commits:

![grafik](https://github.com/AdguardTeam/HostlistsRegistry/assets/104343908/46028924-3525-4a6b-aa06-2dab53b88de3)

**Comment by hbednar** [comment]
@hagezi 
Ok yes your right, it looks like the activity on the  repo is automated.
Looking on their other repos i think this is the new supported links.

https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist#raw-file-sources
