### ISSUE TITLE
Add "Clubhouse" to Blocked services

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/HostlistsRegistry#225]
### Prerequisites

- [X] The service is not included in the list of [Blocked services](https://github.com/AdguardTeam/HostlistsRegistry/blob/main/assets/services.json).
- [X] This is a popular service and it makes sense to have it blocked;

### Service name

Clubhouse

### Explanation

Ability to block/unblock "Clubhouse" (The social audio app – https://www.clubhouse.com/)

**Comment by sayedarifuddin** [comment]
appreciate it.
