### ISSUE TITLE
Add List-TR DNS

### ISSUE THREAD

**Issue by hahmetcakir** [AdguardTeam/HostlistsRegistry#23]
List URLs
https://www.fanboy.co.nz/fanboy-turkish.txt
https://raw.githubusercontent.com/bkrucarci/turk-adlist/master/filters/turkish_generic_content_blocker.txt
https://raw.githubusercontent.com/bkrucarci/turk-adlist/master/filters/I-Do-Not-Want-Your-Mobile-App.txt
https://raw.githubusercontent.com/bkrucarci/turk-adlist/master/hosts

**Comment by ameshkov** [comment]
First three is for traditional ad blockers.

https://github.com/bkrucarci/turk-adlist/ seems okay for a DNS blocklist though.

**Comment by ameshkov** [comment]
Hi @bkrucarci, do you mind if we add your blocklist to the list of available in AdGuard DNS and AdGuard Home?

**Comment by bkrucarci** [comment]
> Hi @bkrucarci, do you mind if we add your blocklist to the list of available in AdGuard DNS and AdGuard Home?

I harvested the Turk-Adlist Host filter by myself and copy-paste rules from AdGuard Turkish filter. You are all free with my filters. Do whatever you want to fight ads & trackers 💯 No problem Andrey 👍🏻 Thanks for adding this. Other suggested filters ,which by the issue opener, may be dangerous (too generic).

Regards,
