### ISSUE TITLE
Adblock Warning Removal List

### ISSUE THREAD

**Issue by User4531** [AdguardTeam/HostlistsRegistry#234]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

Adblock Warning Removal List

### Blocklist category

Ad blocking

### Homepage

https://github.com/easylist/antiadblockfilters

### Explanation

A blocklist for blocking adblock warning banners or pop-ups.
This has to be a possible blocklist, because with this list you do not have the annoying adblock removal warnings anymore.
The list can be find [here](https://easylist-downloads.adblockplus.org/antiadblockfilters.txt)

**Comment by Sergey-Lyapin** [comment]
Hello @User4531

The blocklist should be oriented towards DNS-level content blockers. There is a different [repo](https://github.com/AdguardTeam/FiltersRegistry) for browser content blockers.

And we already have that filter there:
https://github.com/AdguardTeam/FiltersRegistry/tree/master/filters/ThirdParty/filter_207_AdblockWarningRemovalList
