### ISSUE TITLE
Add filter version to metadata

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/HostlistsRegistry#235]
### Issue details

Metadata in https://filters.adtidy.org/dns/filters.json does not contain version tag.

Maybe [code](https://github.com/AdguardTeam/HostlistsRegistry/blob/4b32e629682e4576471d5cb219d88bc554638b0d/hostlists-builder/index.js#L247) (this is a part) from FiltersRegistry can be used.

**Comment by ameshkov** [comment]
DNS filters are not supposed to have a version
