### ISSUE TITLE
Polish filters for pihole not updating 

### ISSUE THREAD

**Issue by KnightmareVIIVIIXC** [AdguardTeam/HostlistsRegistry#236]
Source shows an update from today but Adguard DNS shows updated 7 days ago.

{
  "name": "POL: Polish filters for Pi-hole",
  "description": "Polish filters for Pi-hole.",
  "homepage": "https://www.certyficate.it/",
  "sources": [
    {
      "name": "Polish filters for Pi-hole",
      "source": "https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-pihole-filters/hostfile.txt",
      "type": "hosts",
      "transformations": [
        "Validate"
      ]
    }
  ],
  "transformations": [
    "Deduplicate",
    "Compress"
  ]
}

**Comment by Sergey-Lyapin** [comment]
I suppose that's because  there are no new rules coming out.

Hello @MajkiIT @xxcriticxx
There seems to be something wrong with this list, in it each rule is repeated 116 times.
https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-pihole-filters/hostfile.txt

**Comment by MajkiIT** [comment]
I will check it. Thanks.

**Comment by antek821** [comment]
Hi @MajkiIT . Did you manage to check what the issue is? I see that now every rule is repeated 118 times already. 

In Adguard DNS, the last list update is from 27 days ago

**Comment by MajkiIT** [comment]
Unfortunately, I'm on vacation. I'll be home on Tuesday and I'll get to it right away.

**Comment by KnightmareVIIVIIXC** [comment]
This is updating now, unless I stumbled upon another issue.
