### ISSUE TITLE
Problem with "CHN: AdRules DNS List"

### ISSUE THREAD

**Issue by SrCroqueta** [AdguardTeam/HostlistsRegistry#239]
You should update **_"assets/filter_29.txt"_** and remove **_"discord.gg"_**. If that filter is enable any person who will use Discord will not be allow to connect to it. I'm guessing this is an error and they added it to the filter by a mistake.

**Comment by TonyRL** [comment]
From some unknown reasons, legitimate domains are added in https://github.com/AdguardTeam/HostlistsRegistry/commit/69f45d43f69fc9af10378e0888f7472880119db4.
Just a few examples:
```
||4chan.org^
||ap.org^
||blogspot.com^
```
Part of the [allow-domains-list.txt](https://github.com/Cats-Team/AdRules/blob/main/allow-domains-list.txt) is added as blocklist.
