### ISSUE TITLE
Add Mercado Livre, Aliexpress and Shein

### ISSUE THREAD

**Issue by eduardoaddad** [AdguardTeam/HostlistsRegistry#243]
### Prerequisites

- [X] The service is not included in the list of [Blocked services](https://github.com/AdguardTeam/HostlistsRegistry/blob/main/assets/services.json).
- [X] This is a popular service and it makes sense to have it blocked;

### Service name

Add Mercado Livre + Aliexpress and Shein

### Explanation

Add Mercado Livre,  Aliexpress and Shein

**Comment by Alex-302** [comment]
Please do not mix few companies in one issue.

**Comment by CYAsistemas** [comment]
Is possible add the new streaming service from mercadolibre, mercado play
