### ISSUE TITLE
Add Streamings

### ISSUE THREAD

**Issue by eduardoaddad** [AdguardTeam/HostlistsRegistry#244]
### Prerequisites

- [X] The service is not included in the list of [Blocked services](https://github.com/AdguardTeam/HostlistsRegistry/blob/main/assets/services.json).
- [X] This is a popular service and it makes sense to have it blocked;

### Service name

Add Streamings

### Explanation

Add services:
Globoplay (Brazil, Europe US, Japan and Australia)
UOL Play (Brazil)
Canais Globo (Brazil)
Discovey+ (International)
CNN GO (US)
Pluto TV (International)
Samsung TV (International)
LG Channels (International)
DGO/DirecTV Go (International)
Nintendo =Nintendo 
Star+ (Latin American)
Paramount+ (International)
Looke (Brazil)
Apple TV (International)
AT&T TV (US)
STARZPLAY/LIONSGATE+ (International)
Vivo Play (Brazil)
Claro tv+ (Latin American)
ESPN+ (US)
MAX (HBO Max OLD)
Conmebol TV (Latin American)
FIFA+(International)

**Comment by CYAsistemas** [comment]
Is possible add the new streaming service from mercadolibre, mercado play

**Comment by Alex-302** [comment]
One service - one issue. Do not mix different service in one.
