### ISSUE TITLE
Add AIO-Firebog-Blocklists filter

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/HostlistsRegistry#258]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

AIO-Firebog-Blocklists

### Blocklist category

Trackers blocking

### Homepage

https://github.com/KnightmareVIIVIIXC/AIO-Firebog-Blocklists

### Explanation

Transferred from https://github.com/AdguardTeam/AdGuardDNS/issues/630

**Comment by Sergey-Lyapin** [comment]
Hello @KnightmareVIIVIIXC

Thanks for the suggestion of your lists.
But they don't fit the popularity criteria at the moment.
https://github.com/AdguardTeam/HostlistsRegistry#what-blocklists
```
The blocklist should be relatively popular, meaning:

if there is a repository on GitHub, the number of stars should be at least 50.
```

**Comment by Sergey-Lyapin** [comment]
NoTracking blocklist will eventually be removed. Thank you for letting us know.
https://github.com/AdguardTeam/HostlistsRegistry/pull/259
