### ISSUE TITLE
Blocklist Suggestion | Regional Russia

### ISSUE THREAD

**Issue by sp1kery** [AdguardTeam/HostlistsRegistry#26]
And may be other regional lists needed too.
https://github.com/AdguardTeam/FiltersRegistry/tree/master/filters/filter_1_Russian
Thank you!

**Comment by ameshkov** [comment]
This filter is already included into `AdGuard DNS filter`.

**Comment by person2217** [comment]
But don't know why, it doesn't work. I only enabled the adguard dns filter on the ios side. There is still a chance that this website will have ads.
https://bkrs.info/slovo.php?ch=Дом

**Comment by person2217** [comment]
But don't know why, it doesn't work. I only enabled the adguard dns filter on the ios side. There is still a chance that this website will have ads.
https://bkrs.info/slovo.php?ch=Дом
@ameshkov

**Comment by person2217** [comment]
In fact, adding this filter rule works. https://filters.adtidy.org/ios/filters/1_optimized.txt
