### ISSUE TITLE
Let us add blocklists 

### ISSUE THREAD

**Issue by heli-aviator** [AdguardTeam/HostlistsRegistry#266]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

NSAblocklist

### Blocklist category

Malware&phishing blocking

### Homepage

https://www.libhunt.com/r/NSABlocklist-pi-hole-edition

### Explanation

I would like to add my own blocklists

**Comment by Sergey-Lyapin** [comment]
Hello, @heli-aviator

Looks like this list has been unsupported for 3 years now. So it doesn't meet our criteria for adding lists.

**Comment by Sergey-Lyapin** [comment]
At the moment it is not possible to add your own filters and this feature is not planned in the near future. 
You can use user rules, but there is a 1000 rules limit.
