### ISSUE TITLE
Blocklist suggestion | fuckfuckadblock

### ISSUE THREAD

**Issue by orakaumek** [AdguardTeam/HostlistsRegistry#28]
Here's the link to their repo https://github.com/bogachenko/fuckfuckadblock, It has 694 stars, and the developer updates it frequently, they also have multiple lists as per requirements.

**Comment by bogachenko** [comment]
>the developer updates it frequently

 Not as much as I would like.
***
and this topic has already been discussed https://github.com/AdguardTeam/FiltersRegistry/issues/196

**Comment by ameshkov** [comment]
Not a DNS-level blocklist
