### ISSUE TITLE
Improve Spotify bock service 

### ISSUE THREAD

**Issue by Freebase394** [AdguardTeam/HostlistsRegistry#282]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;

### Blocklist name

Improve Spotify bock service

### Blocklist category

Other

### Homepage

https://www.spotify.com/

### Explanation

If I select to block spotify with AdGuardHome . The spotyfy App android keeps playing
These are the extra domains:

a1931.dscgi3.akamai.net
a239.gi3.akamai.net
a239.gi3.akamai.net
a1051.dscw154.akamai.net
e3528.dscg.akamaiedge.net
a2047.dscapi9.akamai.net
e12919.dscd.akamaiedge.net
e7248.dscb.akamaiedge.net
e4805.dsca.akamaiedge.net
e4805.dsca.akamaiedge.net
e673.dsce9.akamaiedge.net
img-s-msn-com.akamaized.net
img-s-msn-com.akamaized.net
a1847.dscapi6.akamai.net
e673.dsce9.akamaiedge.net
a1802.dscw154.akamai.net
img-s-msn-com.akamaized.net
img-s-msn-com.akamaized.net
img-s-msn-com.akamaized.net
img-s-msn-com.akamaized.net
a1259.dscg1.akamai.net
a1838.dscw154.akamai.net
a1838.dscw154.akamai.net
e673.dscx.akamaiedge.net
e35904.f.akamaiedge.net

**Comment by Sergey-Lyapin** [comment]
Hello @Freebase394

I tested the Spotify app for Android with Spotify service blocking enabled in AdGuard DNS.

If you enable the lock during playback, you can still listen to a few songs, but after a while playback stops and the app is no longer usable.

If you open the application after the lock has been activated, song playback does not work.
Also, authorization is not possible when the lock is enabled.

So I think the blocking is working as it should.

**Comment by Freebase394** [comment]
> Hello @Freebase394
> 
> I tested the Spotify app for Android with Spotify service blocking enabled in AdGuard DNS.
> 
> If you enable the blocking during playback, you can still listen to a few songs, but after a while playback stops and the app is no longer usable.
> 
> If you open the application after the lock has been activated, song playback does not work. Also, authorization is not possible when the lock is enabled.
> 
> So I think the blocking is working as it should.

Many thanks for your time! 
Maybe it's something I'm doing wrong on my end! 

I will try again, and adjust the new settings as needed !
