### ISSUE TITLE
Addition of EasyList to AdGuardDNS

### ISSUE THREAD

**Issue by abhinabgogoi** [AdguardTeam/HostlistsRegistry#293]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

EasyList

### Blocklist category

Ad blocking, Trackers blocking, Other

### Homepage

https://github.com/easylist/easylist

### Explanation

Please include this blocklist in new adguard dns blocklist as most of the annoyances has to be manually filtered. Thank you

**Comment by Sergey-Lyapin** [comment]
Hello @abhinabgogoi

The blocklist should be oriented towards DNS-level content blockers. There is a different [repo](https://github.com/AdguardTeam/FiltersRegistry) for browser content blockers.

And we already have that filter there:
https://github.com/AdguardTeam/FiltersRegistry/tree/master/filters/ThirdParty/filter_101_EasyList
