### ISSUE TITLE
Can CSS elements be blocked using AdGuard DNS filtering rule?

### ISSUE THREAD

**Issue by abhinabgogoi** [AdguardTeam/HostlistsRegistry#294]
Can you please confirm if there is a feature to block css element like 
`##ins.adsbygoogle` 
I have the same rules in the browser extension version where it works but it doesnot seem to be registered as blocked, rather it is categorised as custom in Adguard DNS  user rules. Please do inform me if there  is a way around as I didn't find any topics regarding blocking CSS elements in the documentation-`https://adguard-dns.io/kb/general/dns-filtering-syntax/`. In most cases the ads are not showing but a empty box is showing which I am unable to remove

**Comment by Sergey-Lyapin** [comment]
Hello @abhinabgogoi 

With DNS filtering, there is no way to hide CSS elements. Please install the AdGuard ad blocker to do this.
