### ISSUE TITLE
Whitelists section

### ISSUE THREAD

**Issue by balupton** [AdguardTeam/HostlistsRegistry#31]
I don't have the expertise to send a PR for this report, however [Honey](https://balupton.com/honey) which is a discount finder, [requires a whitelist](
https://help.joinhoney.com/article/303-how-do-i-whitelist-honey-on-my-ad-blocker-so-i-can-still-earn-honey-gold) to function:

```
https://www.joinhoney.com/whitelist/honey-smart-shopping.txt
```

Would be nice if it was added here, so that it could be easily enabled on [AdGuard DNS](https://adguard-dns.io/en/dashboard/settings/blocklist) and inside the AdGuard apps.

**Comment by ameshkov** [comment]
Tbh, I am not too fond of adding this kind of whitelists to the recommended filter lists.

Let's see if this gets upvoted and how many other popular whitelists there are.

**Comment by ameshkov** [comment]
Not upvoted at all after all.
