### ISSUE TITLE
Sort objects in services.json alphabetically by the 'name' property

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/HostlistsRegistry#311]
Services in AdGuard Private DNS are not sorted.

Current `https://github.com/AdguardTeam/HostlistsRegistry/blob/main/assets/services.json` is used by AdGuards, so can be used as a resulting file. Source file must be located in another place or with another name.

**Comment by ameshkov** [comment]
Here's what I suggest:

1. Add `services` folder
2. Every service should be a separate json file there
3. Change the build process so that `assets/services.json` was composed automatically from those small jsons.
4. Also, add validation for the SVG images.

**Comment by Alex-302** [comment]
Also `readme` must be updated.
