### ISSUE TITLE
Notracking block list ended support and should be removed 

### ISSUE THREAD

**Issue by ijuliank** [AdguardTeam/HostlistsRegistry#313]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

Title

### Proposed solution

Remove the filter

### Additional information

No

**Comment by Alex-302** [comment]
Moved to correct place.

**Comment by Sergey-Lyapin** [comment]
Thanks for the info, this list will most likely be removed in the next month.
https://github.com/AdguardTeam/HostlistsRegistry/pull/259
