### ISSUE TITLE
Add Star+

### ISSUE THREAD

**Issue by eduardoaddad** [AdguardTeam/HostlistsRegistry#315]
### Prerequisites

- [X] The service is not included in the list of [Blocked services](https://github.com/AdguardTeam/HostlistsRegistry/blob/main/assets/services.json).
- [X] This is a popular service and it makes sense to have it blocked;

### Service name

Star+

### Explanation

Official website: https://www.starplus.com/

**Comment by Sergey-Lyapin** [comment]
Star+ it is related to Disney+ and already included in Disney+  service. 

Also Star+ can not be blocked safely separate from Disney+ so we decided to block them together as Disney+.
