### ISSUE TITLE
Samsung TV

### ISSUE THREAD

**Issue by eduardoaddad** [AdguardTeam/HostlistsRegistry#317]
### Prerequisites

- [X] The service is not included in the list of [Blocked services](https://github.com/AdguardTeam/HostlistsRegistry/blob/main/assets/services.json).
- [X] This is a popular service and it makes sense to have it blocked;

### Service name

Samsung TV

### Explanation

Official website: https://www.samsung.com/us/televisions-home-theater/tvs/tvplus

**Comment by Sergey-Lyapin** [comment]
Hello @eduardoaddad
What domains should we block? I don't have an android TV to check.

**Comment by eduardoaddad** [comment]
Samsung TV (Tizen OS) or Android 

- https://us-image.samsungtvplus.com
- https://us-api.samsungtvplus.com for United States 
- https://samsungtvplus.com

**Comment by eduardoaddad** [comment]
Do you want me to include all the country links available?

@Sergey-Lyapin

**Comment by eduardoaddad** [comment]
rakuten-euronews-5-de.samsung.wurl.tv

This is also used for live content

**Comment by eduardoaddad** [comment]
I'll test it to see if it works

**Comment by eduardoaddad** [comment]
kr-api.mcsvc.samsung.com

In European versions this domain is also used

Europe:
https://qoe.samsungcloud.tv

**Comment by Sergey-Lyapin** [comment]
The service was added, thank you
