### ISSUE TITLE
Add MAX

### ISSUE THREAD

**Issue by eduardoaddad** [AdguardTeam/HostlistsRegistry#318]
### Prerequisites

- [X] The service is not included in the list of [Blocked services](https://github.com/AdguardTeam/HostlistsRegistry/blob/main/assets/services.json).
- [X] This is a popular service and it makes sense to have it blocked;

### Service name

MAX

### Explanation

Official website: https://www.max.com

**Comment by lex-obrien** [comment]
Isn't Max the same as HBO Max: https://github.com/AdguardTeam/HostlistsRegistry/blob/873665a0d426838f0f3590f3c101f7557d2bbf79/assets/services.json#L1440 ?

**Comment by Sergey-Lyapin** [comment]
We'll rename the service when HBO Max fully migrates to Max.
