### ISSUE TITLE
These blocklists should be added! 

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/HostlistsRegistry#32]
It would be nice to see new lists such as [Lightswitch05 - Ads & Tracking](https://www.github.developerdan.com/hosts/), [Goodbye Ads](https://github.com/jerryn70/GoodbyeAds), [1Hosts (Lite)](https://badmojr.github.io/1Hosts), [notracking](https://github.com/notracking/hosts-blocklists), [oisd full](https://oisd.nl/), [Steven Black](https://github.com/StevenBlack/hosts) and [Anudeep's Blacklist](https://github.com/anudeepND/blacklist).

Edit: I added a few new lists.

Best regards :)

**Comment by checked-wobbles-0p** [comment]
Please!!! this!!

**Comment by Higor-Matos** [comment]
Please!!

**Comment by ameshkov** [comment]
1Hosts and OISD have been added.

Ideally, I'd like to see a different feature request for each list so that we could understand which one of them is really needed.

**Comment by Higor-Matos** [comment]
> 1Hosts and OISD have been added.
> 
> Ideally, I'd like to see a different feature request for each list so that we could understand which one of them is really needed.

Okay, I'll be clearer and talk about the lists

**Comment by checked-wobbles-0p** [comment]
> 1Hosts and OISD have been added.
> 
> Ideally, I'd like to see a different feature request for each list so that we could understand which one of them is really needed.

Any chance for 1Host (Pro)?

**Comment by ameshkov** [comment]
@checked-wobbles-0p please open an issue about it too, let's see how many people would like to use it.

Generally, there's a chance for any list:)
