### ISSUE TITLE
Add Mercado Play 

### ISSUE THREAD

**Issue by eduardoaddad** [AdguardTeam/HostlistsRegistry#331]
### Prerequisites

- [X] The service is not included in the list of [Blocked services](https://github.com/AdguardTeam/HostlistsRegistry/blob/main/assets/services.json).
- [X] This is a popular service and it makes sense to have it blocked;

### Service name

Mercado Play 

### Explanation

Official website: https://play.mercadolivre.com.br

**Comment by Sergey-Lyapin** [comment]
We already have a Mercado Libre service that blocks play.mercadolivre.com.br, among others. In my opinion, there is no point in making play.mercadolivre.com.br a separate service.
