### ISSUE TITLE
Add Romanian Blocklist / Ro to the blocklist page

### ISSUE THREAD

**Issue by soll86** [AdguardTeam/HostlistsRegistry#334]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

RO: Romanian Ad (ROad) Block List Light

### Blocklist category

Ad blocking, Trackers blocking

### Homepage

https://github.com/tcptomato/ROad-Block/tree/master

### Explanation

Complete list is updated here: https://github.com/tcptomato/ROad-Block/blob/master/road-block-filters-light.txt
Homepage of the list: https://github.com/tcptomato/ROad-Block/tree/master
This is a regional list used in multiple locations: Adblock plus / uBlock Origin / etc

**Comment by B-Dog66** [comment]
It would be great to have also this blocklist

**Comment by Sergey-Lyapin** [comment]
Hello, @soll86
According to the requirements the blocklist should be oriented towards DNS-level content blockers. 
There is a different [repo](https://github.com/AdguardTeam/FiltersRegistry) for browser content blockers. And we already have this filter [there](https://github.com/AdguardTeam/FiltersRegistry/tree/master/filters/ThirdParty/filter_236_ROad-Block):
You can enable it in AdGuard Apps and browser extensions.
