### ISSUE TITLE
Unblocked Domains Despite Enabling TikTok Blocking in AdGuard Home

### ISSUE THREAD

**Issue by gyCfjSnO** [AdguardTeam/HostlistsRegistry#338]
### Prerequisites

- [X] The service is not included in the list of [Blocked services](https://github.com/AdguardTeam/HostlistsRegistry/blob/main/assets/services.json).
- [X] This is a popular service and it makes sense to have it blocked;

### Service name

TikTok

### Explanation

I observed that despite enabling the TikTok blocking service in AdGuard Home, these domains appeared as processed in the logs, indicating they were not blocked. Should the following domains be added for more comprehensive coverage?

```
*.tiktokcdn-us.com
*.ttlivecdn.com.c.bytefcdn-oversea.com
*.ttlivecdn.com
*.ibytedtos.com
*.ibyteimg.com
```

**Comment by Sergey-Lyapin** [comment]
Hello @trmdi 
I believe updates are already available.

**Comment by kKen94** [comment]
<img width="1222" height="689" alt="Image" src="https://github.com/user-attachments/assets/1ea8634f-642e-4c3b-b3ad-908fb44ff923" />

Hello everyone, I reopen this since is still an actual issue
