### ISSUE TITLE
HaGeZi's Allowlist Referral - categorize as allowlist, not blocklist

### ISSUE THREAD

**Issue by timkgh** [AdguardTeam/HostlistsRegistry#342]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

HaGeZi's Allowlist Referral

### Blocklist category

Other

### Homepage

https://adguardteam.github.io/HostlistsRegistry/assets/filter_45.txt

### Explanation

Please introduce an **allowlist** category. Some of these lists are meant to *allow* domains, not block them, e.g.
https://adguardteam.github.io/HostlistsRegistry/assets/filter_45.txt

See https://github.com/AdguardTeam/AdGuardHome/issues/6207

**Comment by Sergey-Lyapin** [comment]
Hello @timkgh

We have decided not to add such a category for now, if a few new allowlists will be added we will look into it again.
