### ISSUE TITLE
WhatsApp Channels

### ISSUE THREAD

**Issue by UpTheDesign** [AdguardTeam/HostlistsRegistry#353]
### Prerequisites

- [X] The service is not included in the list of [Blocked services](https://github.com/AdguardTeam/HostlistsRegistry/blob/main/assets/services.json).
- [X] This is a popular service and it makes sense to have it blocked;

### Service name

WhatsApp Channels

### Explanation

WhatsApp has recently released "Channels" where you can browse or follow celebs etc. (many similarities to Instagram).
For those people who want to use WhatsApp strictly as a messaging app and not as a social media time-consumer, finding a way to block the new channel feature will be amazing!
Possibly make the option to block WhatsApp Status Updates too, but those are not as bad as they are only updates from people you have mutually saved in your contacts, whereas through channels, the possibilities and exposure is endless.

**Comment by Sergey-Lyapin** [comment]
Hello, @UpTheDesign
I'm guessing that's technically impossible. The same domains are used for messenger and channels.
