### ISSUE TITLE
Smart TV Blocklists 

### ISSUE THREAD

**Issue by Mr-McMuffin** [AdguardTeam/HostlistsRegistry#357]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

PiHoleBlocklist

### Blocklist category

Ad blocking, Other

### Homepage

https://github.com/Perflyst/PiHoleBlocklist

### Explanation

Please either use this list or make your own for Smart TV / Device Blocklists, needed as manually using these currently to avoid ads on google TV. 

Need updates asap.

**Comment by Sergey-Lyapin** [comment]
Hello, @Mr-McMuffin. Sorry for the long delay.

We already have this list called "Perflyst and Dandelion Sprout's Smart-TV Blocklist"
![tv](https://github.com/AdguardTeam/HostlistsRegistry/assets/18536328/5f1c869c-99c7-438b-98b9-a2f22c6f5ee3)
