### ISSUE TITLE
Remove Energized Spark

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/HostlistsRegistry#36]
I feel the matter is urgent enough that https://github.com/AdguardTeam/HostlistsRegistry/commit/4b35ee6ce18a6466f59ddd4caa525ad0c1e4da8e#commitcomment-74500604 alone doesn't get the point through fast enough.

In addition to `https://github.com/EnergizedProtection/block/issues/916`, Energized Protection is a mess where the one remaining admin doesn't do anything (All of the commits are just his bot), other team members don't have sufficient rights to fix the issue backlog (Take my word for it. I was one of those team members for a while), and I don't recommend using the list for any purpose by any person. It was already [changed from default to non-default in Blokada](https://github.com/blokadaorg/blokada/issues/781) due to all this if I understand things correctly, and is [reportedly close to being removed from PersonalDNSblocker](https://github.com/IngoZenz/personaldnsfilter/issues/212) for the same reasons.

**Comment by ameshkov** [comment]
Argh, removing a list is a much more problematic thing than adding it.
