### ISSUE TITLE
False positives Adguard Home parental control

### ISSUE THREAD

**Issue by JuanRodenas** [AdguardTeam/HostlistsRegistry#377]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

Adguard Home parental control

### Blocklist category

Other

### Homepage

False positives Adguard Home parental control

### Explanation

Adguard Home parental controls are blocking functional URLs. Attached is a screenshot.

![imagen](https://github.com/AdguardTeam/HostlistsRegistry/assets/95724863/3096bc85-87d1-4325-bbbf-bd5622fad86b)

Some of the URLs are:

```
update.intl.miui.com
push.services.mozilla.com
wallhere.com
detectportal.firefox.com
api.accounts.firefox.com
updates.push.services.mozilla.com
```

I hope they fix it soon.

Best regards

**Comment by ameshkov** [comment]
Fixed these all, should soon be updated.
