### ISSUE TITLE
1Hosts (Lite): wrong source URL used.

### ISSUE THREAD

**Issue by badmojr** [AdguardTeam/HostlistsRegistry#38]
@ameshkov
The current URL points to 1Hosts (mini).
It should point to the correct source , which is `https://badmojr.gitlab.io/1hosts/Lite/adblock.txt`

![Lite_wrong-url](https://user-images.githubusercontent.com/40524316/170412033-a0732ee5-719b-4f95-89d8-e08c3341001a.PNG)

**Comment by badmojr** [comment]
This [commit](https://github.com/AdguardTeam/HostlistsRegistry/commit/e4266f2000a2926a4b3c0dd251b6300112869d82) introduced the said error above.

see also: https://raw.githubusercontent.com/AdguardTeam/HostlistsRegistry/main/filters/general/filter_24_1Hosts_Lite/filter.txt

**Comment by ameshkov** [comment]
Thank you for checking it!
