### ISSUE TITLE
GOODBYEADS

### ISSUE THREAD

**Issue by Padge007** [AdguardTeam/HostlistsRegistry#381]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [ ] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

GOODBYEADS

### Blocklist category

Ad blocking

### Homepage

https://github.com/jerryn70/GoodbyeAds

### Explanation

Ive seen loads of people on reddit saying to use it and its very popular with the adblocking community and it was recommended to me by a friend on reddit

**Comment by Sergey-Lyapin** [comment]
Hello @Padge007
Why did you close the issue?

**Comment by Sergey-Lyapin** [comment]
Ok, I see that Alex closed your Pull Request because this list is a compilation. Well, in this case we will not add it.

**Comment by Padge007** [comment]
Because Alex said you weren’t interested in a bunch of filters is basically how he put itOn 25 Oct 2023, at 14:18, Sergey ***@***.***> wrote:﻿
Ok, I see that Alex closed your Pull Request because this list is a compilation. Well, in this case we will not add it.
