### ISSUE TITLE
USOM - Top misleading site block list

### ISSUE THREAD

**Issue by Soickan** [AdguardTeam/HostlistsRegistry#386]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

Add list: USOM - Official Turk Cyber Block Center (www.usom.gov.tr)

### Proposed solution

Hi,

Add please USOM - Official Turk Cyber Block Center (http://www.usom.gov.tr) block list. There is no ad blocking in the list. The list includes a list of fake and misleading sites. It is mostly updated hourly.

You can learn the details of blocked sites at https://www.usom.gov.tr/adres

This list address: https://www.usom.gov.tr/url-list.txt

Thanks

**Comment by Alex-302** [comment]
@Soickan Moved to the correct repository.

**Comment by Sergey-Lyapin** [comment]
Hello @Soickan, thank you for suggestion.
Here is blocklist [requirements](https://github.com/AdguardTeam/HostlistsRegistry?tab=readme-ov-file#-what-blocklists-can-be-added-here)

How can I check this list against these criteria?

```
The blocklist should have a place for receiving user complaints and holding discussions, such as a repository on github.com, or a public website/forum.

The blocklist should be relatively popular, meaning:
- if there is a repository on GitHub, the number of stars should be at least 50.
- if there is no repository on GitHub, the number of reported issues and discussions should be at least 10 per month.
- the blocklist should be actively supported for at least 6 months.

The blocklist should be regularly updated with at least 10 updates per month.
```

**Comment by Alex-302** [comment]
Hm. I don't see working domains below 20k line. The most domains are blocked/dead.

**Comment by Soickan** [comment]
Since they are mostly misleading (phishing) sites, when they are detected, the site owners close the site. Therefore, there will be old sites that do not work. This is, in a way, proof that the detection of sites is quick.

**Comment by Alex-302** [comment]
It has more than 250k domains, and the most of that domains are dead/unregistered.
Why don't they remove or move to another file domains, that are dead?

**Comment by Soickan** [comment]
> It has more than 250k domains, and the most of that domains are dead/unregistered. Why don't they remove or move to another file domains, that are dead?

First of all, although it is officially detected and blocked, it continues to prevent phishing by remaining on the list.

Other ad blocking filters do not guarantee a 100% active domain. I see that retroactive cleaning is not done much in these filters.

**Comment by hagezi** [comment]
The active domains are included in my Threat Intelligence Feed list. The USOM also has a few false positive domains from time to time, these are also filtered out.

The TIF is available in AdGuard DNS.

**Comment by hagezi** [comment]
Stats from the last TIF build:

```
 Nr | Included | Dead | Removed |   Count | URL/File
136 |      25% |  75% |      0% |  250898 | https://www.usom.gov.tr/url-list.txt
```

75% Dead domains ...

**Comment by Alex-302** [comment]
@hagezi Which tool do you use to check dead domains? 3p or your own?

**Comment by hagezi** [comment]
@Alex-302 I check this myself with my own script against the Google DNS. My lists are checked once a month. I also check the deadlist once a month to see if dead domains are active again. I can make the list of dead domains available if required.

**Comment by Sergey-Lyapin** [comment]
The active domains on this list are included in Hagezi's Threat Intelligence Feed list, so we won't add this list separately.
