### ISSUE TITLE
AWAvenue Adblock Rule

### ISSUE THREAD

**Issue by TG-Twilight** [AdguardTeam/HostlistsRegistry#393]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [x] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

秋风广告规则

### Blocklist category

Ad blocking

### Homepage

https://github.com/TG-Twilight/AWAvenue-Adblock-Rule

### Explanation

Using Adblock syntax, it fights (blocks) various rogue ad SDKs in Android apps at the network level and prevents them from loading, so as to achieve the purpose of de-advertising. It is currently known to be effective against a variety of advertising SDKs.

**Comment by Sergey-Lyapin** [comment]
https://github.com/AdguardTeam/HostlistsRegistry/pull/408

**Comment by Sergey-Lyapin** [comment]
Most likely the filter will be moved to the prod next week.

**Comment by TG-Twilight** [comment]
> Most likely the filter will be moved to the prod next week.

thank you！
