### ISSUE TITLE
DynDNS

### ISSUE THREAD

**Issue by KnightmareVIIVIIXC** [AdguardTeam/HostlistsRegistry#397]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

HaGeZi's DynDNS Blocklist

### Blocklist category

Other

### Homepage

https://github.com/hagezi/dns-blocklists

### Explanation

Might as well add this as an option to users, since it claims to protect:
A blocklist for blocking dynamic DNS services to protect against malicious use in phishing campaigns and others.

**Comment by hagezi** [comment]
https://github.com/AdguardTeam/HostlistsRegistry/issues/356

**Comment by KnightmareVIIVIIXC** [comment]
Ah two votes

**Comment by KnightmareVIIVIIXC** [comment]
Fix the a vs an

**Comment by Sergey-Lyapin** [comment]
Duplicate.
