### ISSUE TITLE
German DNS Filter List

### ISSUE THREAD

**Issue by awagdi0** [AdguardTeam/HostlistsRegistry#398]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

https://easylist.to/easylistgermany/easylistgermany.txt

### Blocklist category

Ad blocking, Trackers blocking

### Homepage

https://easylist.to/easylistgermany/easylistgermany.txt

### Explanation

Please either use this German ads list or make your own for German  Blocklists, as needed as manually using these currently to avoid ads

Need updates asap.

Thanks!

**Comment by Sergey-Lyapin** [comment]
Hello, @awagdi0
This blocklist is not oriented towards DNS-level content blockers.
I would recommend using the AdGuard DNS filter, which already [contains](https://github.com/AdguardTeam/AdGuardSDNSFilter?tab=readme-ov-file#dns-filter-structure) domains from EasyList Germany and AdGuard German filter.
