### ISSUE TITLE
YouTube being forced to restricted mode when Safe Search is Off

### ISSUE THREAD

**Issue by redstormsju** [AdguardTeam/HostlistsRegistry#399]
Hello all,

All of a sudden YouTube is being forced by my AdGuard instance to be on restricted mode.  I have safe search off so I am not sure why this is happening. This occurred just today and  has been fine before today….no changes were made to my AdGuard settings. Any thoughts on what’s going on or a fix?

**Comment by ameshkov** [comment]
Hi, what blocklists do you have enabled in AG DNS?

**Comment by redstormsju** [comment]
Hello,

Thank you for the response.  Below are the blocklists enabled on my AG
DNS...at this point the issue resolved itself with me doing nothing, but it
is still odd that my AdGuard instance forced youtube to go into
restricted mode with Safe Searched turned off on my adguard instance.

AdGuard DNS filter
https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt
58,461
November 27, 2023 at 08:15
AdAway Default Blocklist
https://adguardteam.github.io/HostlistsRegistry/assets/filter_2.txt
6,540
November 27, 2023 at 08:15
1Hosts (Lite)
https://adguardteam.github.io/HostlistsRegistry/assets/filter_24.txt
66,322
November 27, 2023 at 08:15
1Hosts (mini)
https://adguardteam.github.io/HostlistsRegistry/assets/filter_38.txt
68,405
November 27, 2023 at 08:15
Dan Pollock's List
https://adguardteam.github.io/HostlistsRegistry/assets/filter_4.txt
11,636
November 27, 2023 at 08:15
HaGeZi Personal Black & White
https://adguardteam.github.io/HostlistsRegistry/assets/filter_34.txt
179,380
November 27, 2023 at 08:15
OISD Blocklist Small
https://adguardteam.github.io/HostlistsRegistry/assets/filter_5.txt
40,136
November 27, 2023 at 08:15
The NoTracking blocklist
https://adguardteam.github.io/HostlistsRegistry/assets/filter_32.txt
419,952
November 27, 2023 at 08:16
OISD Blocklist Big
https://adguardteam.github.io/HostlistsRegistry/assets/filter_27.txt
209,647
November 27, 2023 at 08:16
Peter Lowe's Blocklist
https://adguardteam.github.io/HostlistsRegistry/assets/filter_3.txt
3,716
November 27, 2023 at 08:16
Steven Black's List
https://adguardteam.github.io/HostlistsRegistry/assets/filter_33.txt
160,199
November 27, 2023 at 08:16
Dandelion Sprout's Game Console Adblock List
https://adguardteam.github.io/HostlistsRegistry/assets/filter_6.txt
10
November 27, 2023 at 08:16
WindowsSpyBlocker - Hosts spy rules
https://adguardteam.github.io/HostlistsRegistry/assets/filter_23.txt
347
November 27, 2023 at 08:16
Perflyst and Dandelion Sprout's Smart-TV Blocklist
https://adguardteam.github.io/HostlistsRegistry/assets/filter_7.txt
159
November 27, 2023 at 08:16
Phishing URL Blocklist (PhishTank and OpenPhish)
https://adguardteam.github.io/HostlistsRegistry/assets/filter_30.txt
22,819
November 27, 2023 at 08:16
Dandelion Sprout's Anti-Malware List
https://adguardteam.github.io/HostlistsRegistry/assets/filter_12.txt
22,080
November 27, 2023 at 08:16
NoCoin Filter List
https://adguardteam.github.io/HostlistsRegistry/assets/filter_8.txt
409
November 27, 2023 at 08:16
Scam Blocklist by DurableNapkin
https://adguardteam.github.io/HostlistsRegistry/assets/filter_10.txt
979
November 27, 2023 at 08:16
ShadowWhisperer's Malware List
https://adguardteam.github.io/HostlistsRegistry/assets/filter_42.txt
32,204
November 27, 2023 at 08:16
Stalkerware Indicators List
https://adguardteam.github.io/HostlistsRegistry/assets/filter_31.txt
868
November 27, 2023 at 08:16
The Big List of Hacked Malware Web Sites
https://adguardteam.github.io/HostlistsRegistry/assets/filter_9.txt
13,468
November 27, 2023 at 08:16
Malicious URL Blocklist (URLHaus)
https://adguardteam.github.io/HostlistsRegistry/assets/filter_11.txt
5,664
November 27, 2023 at 08:16

**Comment by ameshkov** [comment]
Quick question: do you have them enabled in AdGuard Home or AdGuard DNS?

**Comment by redstormsju** [comment]
> Quick question: do you have them enabled in AdGuard Home or AdGuard DNS?

I have then enabled in the DNS Blocklist settings of AdGuard Home.

**Comment by ameshkov** [comment]
What upstream DNS server do you have in AdGuard Home? Could it be that safe search is enforced by it and not by AdGuard Home?

**Comment by redstormsju** [comment]
> What upstream DNS server do you have in AdGuard Home? Could it be that safe search is enforced by it and not by AdGuard Home?

These are the upstream dns servers I’m running….how would I find out which one could be the issue?

https://dns10.quad9.net/dns-query
94.140.14.15
94.140.15.16
94.140.14.14
94.140.15.15
https://dns.adguard-dns.com/dns-query
208.67.222.222
208.67.220.220
https://doh.familyshield.opendns.com/dns-query
https://security.cloudflare-dns.com/dns-query
https://family.cloudflare-dns.com/dns-query
1.1.1.2
1.0.0.2
https://adblock.doh.mullvad.net/dns-query
tls://dns.adguard.com

**Comment by ameshkov** [comment]
Why would you need that many?

These are with family protection:
```
94.140.14.15
94.140.15.16
```

Also, familyshield and cloudflare-dns also have some parental control.
I'd generally advise against using several different upstream filtering servers.

Choose something that does not change DNS responses and rely on AdGuard Home for that instead.

**Comment by redstormsju** [comment]
> Why would you need that many?
> 
> These are with family protection:
> 
> ```
> 94.140.14.15
> 94.140.15.16
> ```
> 
> Also, familyshield and cloudflare-dns also have some parental control. I'd generally advise against using several different upstream filtering servers.
> 
> Choose something that does not change DNS responses and rely on AdGuard Home for that instead.

Thank you. I will modify the upstream settings and remove the excess.  I’m still learning, I appreciate all of your feedback in the thread.

**Comment by ameshkov** [comment]
No worries:) General advice would be: keep just two upstreams, the most "unbiased", Google DNS or Cloudflare DNS. AdGuard Home will take care of filtering, you just need an upstream that returns unfiltered results.
