### ISSUE TITLE
False positives Adguard Home parental control

### ISSUE THREAD

**Issue by JuanRodenas** [AdguardTeam/HostlistsRegistry#407]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

Adguard Home parental control

### Blocklist category

Other

### Homepage

False positives Adguard Home parental control

### Explanation

Adguard Home parental controls are blocking functional URLs. Attached is a screenshot.

![firefox](https://github.com/AdguardTeam/HostlistsRegistry/assets/95724863/f6a953ee-ab65-4dbf-a9d0-72ae2a1f0123)

Some of the URLs are:

```
api.accounts.firefox.com
profile.accounts.firefox.com
detectportal.firefox.com
updates.push.services.mozilla.com
www.gravatar.com
0.gravatar.com
secure.gravatar.com
```

I hope they fix it soon.

Best regards

**Comment by Sergey-Lyapin** [comment]
Hello, @JuanRodenas
I can't reproduce this issue at the moment. Is it still relevant?

**Comment by JuanRodenas** [comment]
Hello, @Sergey-Lyapin
I just reactivated the parental control and it is working.
Best regards.
