### ISSUE TITLE
Add Lightswitch05 - Ads & Tracking to Adguard DNS Blocklists

### ISSUE THREAD

**Issue by MaldroidDev** [AdguardTeam/HostlistsRegistry#409]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

Lightswitch05 - Ads & Tracking

### Blocklist category

Ad blocking, Trackers blocking

### Homepage

https://www.github.developerdan.com/hosts/

### Explanation

A programmatically expanded list of hosts used for advertisements and tracking. This is my primary list and I recommend using it.

**Comment by ajp2k13** [comment]
It's in maintenance mode?

https://github.com/lightswitch05/hosts/issues/356

**Comment by Sergey-Lyapin** [comment]
Hello @MaldroidDev
Thank you for the suggestion.
Your list does not formally meet the criterion: `The blocklist should be regularly updated with at least 10 updates per month.`
At this point, the last commit was over a month ago.  If the list is maintained, we will consider adding it.
