### ISSUE TITLE
Add List "Lightswitch05"

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/HostlistsRegistry#42]
Please add lists from:

https://github.com/lightswitch05/hosts

Preferably:
Ads & Tracking
Facebook

**Comment by DandelionSprout** [comment]
At 420,114 entries for a 'Hosts' file, it seems slightly big to me, especially since more than 390,000 of the entries are subdomains of the domains the list aims to block.

**Comment by badmojr** [comment]
duplicate: #27

**Comment by ameshkov** [comment]
The original request was rejected: https://github.com/AdguardTeam/HostlistsRegistry/issues/27#issuecomment-1337761389
