### ISSUE TITLE
Please add https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt to blocklists

### ISSUE THREAD

**Issue by robcazzaro** [AdguardTeam/HostlistsRegistry#433]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

First Party Trackers

### Blocklist category

Trackers blocking

### Homepage

https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt

### Explanation

This list is part of the default for https://diversion.ch/diversion/use/blocking-file-hosts-files.html, commonly used on Asus routers. I'm migrating away from that blocker, and would like to maintain a similar level of ad/tracker blocking

**Comment by Sergey-Lyapin** [comment]
Hello @robcazzaro

This list does not meet the following requirement and its popularity is difficult to assess.
```
- The blocklist should have a place for receiving user complaints and holding discussions, such as a repository on github.com, or a public website/forum.
```
and its popularity is difficult to assess.
```
- The blocklist should be relatively popular, meaning:
  - if there is a repository on GitHub, the number of stars should be at least 50.
  - if there is no repository on GitHub, the number of reported issues and discussions should be at least 10 per month.
  - the blocklist should be actively supported for at least 6 months.
- The blocklist should be regularly updated with at least 10 updates per month.
```
