### ISSUE TITLE
uBlock filters - Ads

### ISSUE THREAD

**Issue by Dvirf8969** [AdguardTeam/HostlistsRegistry#435]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

uBlock filters – Ads

### Blocklist category

Ad blocking

### Homepage

https://cdn.statically.io/gh/uBlockOrigin/uAssetsCDN/main/filters/filters.min.txt

### Explanation

Homepage: https://github.com/uBlockOrigin/uAssets

**Comment by Sergey-Lyapin** [comment]
Hello @Dvirf8969

The blocklist should be oriented towards DNS-level content blockers. There is a different [repo](https://github.com/AdguardTeam/FiltersRegistry) for browser content blockers.
The possibility of adding uBlock lists is discussed [here](https://github.com/AdguardTeam/FiltersRegistry/issues/654).
