### ISSUE TITLE
1Hosts (Pro)

### ISSUE THREAD

**Issue by Dvirf8969** [AdguardTeam/HostlistsRegistry#436]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

1Hosts (Pro)

### Blocklist category

Ad blocking

### Homepage

https://github.com/badmojr/1Hosts

### Explanation

1Hosts (Pro) is Great for overall protection!

**Comment by Glazami** [comment]
+

**Comment by Sergey-Lyapin** [comment]
The filter will be added when this issue is solved: https://github.com/AdguardTeam/AdGuardDNS/issues/758

PR: https://github.com/AdguardTeam/HostlistsRegistry/pull/431
