### ISSUE TITLE
Import Custom filter

### ISSUE THREAD

**Issue by Dvirf8969** [AdguardTeam/HostlistsRegistry#437]
### Prerequisites

- [X] The service is not included in the list of [Blocked services](https://github.com/AdguardTeam/HostlistsRegistry/blob/main/assets/services.json).
- [X] This is a popular service and it makes sense to have it blocked;

### Service name

Custom filter

### Explanation

Hello
Please add the ability to import Custom filters from urls on "Server settings" on Adguard DNS website.
Thanks

**Comment by Sergey-Lyapin** [comment]
Hello @Dvirf8969
At the moment there are no plans to implement such a feature; it is very resource-intensive.
By the way, Adguard Home has such a feature.
