### ISSUE TITLE
"ISR: EasyList Hebrew" - Source list is not updated

### ISSUE THREAD

**Issue by Dvirf8969** [AdguardTeam/HostlistsRegistry#438]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

ISR: EasyList Hebrew

### Blocklist category

Ad blocking

### Homepage

https://github.com/easylist/EasyListHebrew

### Explanation

The current filter "ISR: EasyList Hebrew" is not using the correct updated source list.
It shows on Adguard DNS - 296 rules which on the updated sources it's: about: 1286 rules -
https://raw.githubusercontent.com/easylist/EasyListHebrew/master/EasyListHebrew.txt
Please adjust it
Thank you

**Comment by Sergey-Lyapin** [comment]
Hello, @Dvirf8969
Thanks for your suggestion.
According to the requirements the blocklist should be oriented towards DNS-level content blockers. 
The list you sent the link to is for browser-oriented content blockers.
