### ISSUE TITLE
Add Turkish Bet Hosts

### ISSUE THREAD

**Issue by emrekeles** [AdguardTeam/HostlistsRegistry#440]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

Turkish-Bet-Hosts

### Blocklist category

Ad blocking, Trackers blocking, Malware&phishing blocking, Other

### Homepage

https://github.com/emrekeles/Turkish-Bet-Hosts/tree/main/adguard

### Explanation

- This list is **updated daily** and includes betting companies specific to Turkey. 
- Additionally, this list includes **phishing** betting companies.

**Comment by hagezi** [comment]
@emrekeles I have added the list to my gambling list, which is available for selection in AdGuard DNS.

**Comment by Sergey-Lyapin** [comment]
Hello @emrekeles
I guess if all these domains are already on HaGeZi's Gambling Blocklist, there's no point in adding Turkish Bet Hosts separately.

**Comment by emrekeles** [comment]
I have some findings, they cannot be opened from outside of Turkey. Therefore, it would be better if it was published as a list specific to Turkey.

**Comment by emrekeles** [comment]
> ### Prerequisites
> * [x]  The blocklist is created specifically for DNS-level blockers;
> * [x]  The blocklist is regularly updated (at least 10 updates per month);
> * [x]  The blocklist is known and popular;
> * [x]  The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);
> 
> ### Blocklist name
> Turkish-Bet-Hosts
> 
> ### Blocklist category
> Ad blocking, Trackers blocking, Malware&phishing blocking, Other
> 
> ### Homepage
> https://github.com/emrekeles/Turkish-Bet-Hosts/tree/main/adguard
> 
> ### Explanation
> * This list is **updated daily** and includes betting companies specific to Turkey.
> * Additionally, this list includes **phishing** betting companies.


I have some findings, they cannot be opened from outside of Turkey. Therefore, it would be better if it was published as a list specific to Turkey.

**Comment by emrekeles** [comment]
You can delete it.

**Comment by emrekeles** [comment]
> Hello @emrekeles I guess if all these domains are already on HaGeZi's Gambling Blocklist, there's no point in adding Turkish Bet Hosts separately.


You can delete it issues

**Comment by emrekeles** [comment]
You can delete it issues @hagezi @Sergey-Lyapin @
