### ISSUE TITLE
Add hBlock Blocklist

### ISSUE THREAD

**Issue by krakeni8** [AdguardTeam/HostlistsRegistry#442]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

hBlock

### Blocklist category

Ad blocking, Trackers blocking, Malware&phishing blocking

### Homepage

https://hblock.molinero.dev/

### Explanation

I was a paid user of NextDNS and they offer this blocklist. Now I'm a paid Adguard DNS user and I'm sad to see that this list isn't offered. I hope you will consider adding it. Thank you.

**Comment by Sergey-Lyapin** [comment]
Hello @krakeni8, thanks for the suggestion.
This list is a compilation, and we prefer original lists to compilations.
We recommend using Adguard DNS filter or other available lists for instance HaGeZi's Pro++ Blocklist.
