### ISSUE TITLE
AdGuard_Türkiye_Genişletilmiş_Liste

### ISSUE THREAD

**Issue by AZE-NOVA** [AdguardTeam/HostlistsRegistry#444]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

AdGuard_Turkish_Extended

### Blocklist category

Ad blocking

### Homepage

https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_13_Turkish/filter.txt

### Explanation

Film izleme, streaming siteleri gibi sitelerdeki mosbet, 1xbet, paribahis ve yasa dışı reklamların çoğunu engeller

**Comment by Sergey-Lyapin** [comment]
Hello @AZE-NOVA
Thanks for your suggestion.
According to the requirements the blocklist should be oriented towards DNS-level content blockers.
You can enable AdGuard Turkish filter in our extensions and applications.
