### ISSUE TITLE
EasyList Czech and Slovak

### ISSUE THREAD

**Issue by dagdrommer** [AdguardTeam/HostlistsRegistry#448]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

EasyList Czech and Slovak

### Blocklist category

Ad blocking, Trackers blocking

### Homepage

https://github.com/tomasko126/easylistczechandslovak

### Explanation

EasyList Czech and Slovak is a popular blocklist that specializes in the Czech and Slovak advertising market, so I encourage you to add it to your service.

Thank you very much in advance, I appreciate your services.

Cheers!

**Comment by Sergey-Lyapin** [comment]
Hello @dagdrommer
Thanks for your suggestion.
According to the requirements the blocklist should be oriented towards DNS-level content blockers. 
There is a different [repo](https://github.com/AdguardTeam/FiltersRegistry) for browser content blockers. And we already have this filter [there](https://github.com/AdguardTeam/FiltersRegistry/tree/master/filters/ThirdParty/filter_105_EasyListCzechAndSlovak):
You can enable it in AdGuard Apps and browser extensions.
