### ISSUE TITLE
 Missing syntax or error on some filters

### ISSUE THREAD

**Issue by Raviu56** [AdguardTeam/HostlistsRegistry#449]
Hello,
Sorry for double posting on another repo too as it's confusing where to post, but I assume here as the file directly related to this repo
Simply the syntax on your list here for example:
https://adguardteam.github.io/HostlistsRegistry/assets/filter_12.txt

For those lines starting with column like this:
://ww4.$denyallow=ww4.ikea.com
://ww5.$denyallow=ww5.ikea.com|ww5.msu.ac.zw
://popupblockergold.
://adblock-pro-download.
://142.91.159.
://23.109.150.

And lines starting with dash like this:
-outletcanada.
-norgesalg.com^

Is not documented here https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists or here https://adguard.com/kb/general/ad-filtering/create-own-filters/ and cannot be found here https://adblockplus.org/filter-cheatsheet too

If they are mistaken removes them, if they're some kind of comment use ! as you mention, otherwise if valid add the syntax to the wiki and kb

**Comment by Alex-302** [comment]
Some rules like that can be processed by AdGuard.

![image](https://github.com/user-attachments/assets/fdbe0ae1-6f94-4af0-aa14-629c291fba3f)
