### ISSUE TITLE
Please Add List

### ISSUE THREAD

**Issue by azafrak** [AdguardTeam/HostlistsRegistry#45]
Hi, please add list attach image
![AdList](https://user-images.githubusercontent.com/30311445/170877615-f9b81684-5aa4-4f06-8574-8d40529c84c9.png)

**Comment by ameshkov** [comment]
Hi, please open a separate issue for every list (if it's not already added or opened).

Regarding the screenshot, Fanboy's Annoyance List is not supposed to be used on the DNS level, makes no sense to add it.
