### ISSUE TITLE
Consider removing WindowsSpyBlocker - it hasn't been updated in almost 2 years

### ISSUE THREAD

**Issue by timkgh** [AdguardTeam/HostlistsRegistry#452]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

WindowsSpyBlocker - Hosts spy rules

### Blocklist category

Other

### Homepage

https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt

### Explanation

Consider **removing** WindowsSpyBlocker - it hasn't been updated in almost 2 years
`Updated: 2022-05-16T13:25:00Z02:12`

At this point it just ads a false sense of security.

I'm not sure whether there are better replacements out there.

It should also be removed from AdGuard Home.

**Comment by Sergey-Lyapin** [comment]
Hello,
The list may not have been updated for a long time, but the current rules are relevant and the list developer is going to add new ones, so we decided not to delete this list for now.

P.S. And I don’t know of a worthy replacement.

**Comment by hagezi** [comment]
> P.S. And I don’t know of a worthy replacement.

https://github.com/AdguardTeam/HostlistsRegistry/issues/507

**Comment by KnightmareVIIVIIXC** [comment]
> P.S. And I don’t know of a worthy replacement.

https://github.com/SystemJargon/filters/blob/main/telemetry.txt
