### ISSUE TITLE
OISD NSFW big

### ISSUE THREAD

**Issue by BirdInFire** [AdguardTeam/HostlistsRegistry#453]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

OISD NSWF big

### Blocklist category

Other

### Homepage

https://oisd.nl

### Explanation

Actually I do know you provide your own feature but on apple device (who use your services as profile) the nsfw do not work at all, the domain is detected but not blocked and mostly due to the fact only NXdomain answer properly block it and nearly all adult website showed on my device have a no error answer meaning it block nothing in my case.

This list would allow people like me to block adult content that your integrated list fail to do when we use iCloud relay (and saying to disable it is not a good answer since I'm a paid user from your dns).

**Comment by ChitranshuV** [comment]
+1 Currently there is no NSFW blocklist and this list is regularly updated and comprehensive as well.

**Comment by Sergey-Lyapin** [comment]
Hello,
We don't add NSFW lists because we have our own "Block adult websites" option in the parental control.
