### ISSUE TITLE
Add Brazil malicious domains

### ISSUE THREAD

**Issue by eduardoaddad** [AdguardTeam/HostlistsRegistry#457]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

BR-FILTER: Malicious websites

### Blocklist category

Malware&phishing blocking

### Homepage

https://github.com/eduardoaddad/BR-filter

### Explanation

Add malicious filter made especially for Brazil.

DNS Filter: https://github.com/eduardoaddad/BR-filter/blob/main/Brazil.malicious.domains.txt

**Comment by Sergey-Lyapin** [comment]
Hello @eduardoaddad
Thanks for the suggestion.
This list don't fit the popularity criteria at the moment.
```
- The blocklist should have a place for receiving user complaints and holding discussions, such as a repository on github.com, or a public website/forum.
- The blocklist should be relatively popular, meaning:
  - if there is a repository on GitHub, the number of stars should be at least 50.
  - if there is no repository on GitHub, the number of reported issues and discussions should be at least 10 per month.
  - the blocklist should be actively supported for at least 6 months.
- The blocklist should be regularly updated with at least 10 updates per month.
```
