### ISSUE TITLE
Private IP range blocked by Ad blocklist

### ISSUE THREAD

**Issue by odarriba** [AdguardTeam/HostlistsRegistry#463]
I have discovered that some of our internal AWS ALBs are blocked using AdGuard lists.

The list is: https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt
The IP range filtered by the blocklist is: `10.10.34.*`.

As it is blocked as a IP range and not as a domain name, it is blocking any domain pointing to it.

However, it is a private IP range as per ARIN (check [here](https://www.arin.net/reference/research/statistics/address_filters/)) and I think it shopuld nopt be blocked - no external Ad service can be run on that IP.

Thanks in advance,

**Comment by Sergey-Lyapin** [comment]
Private IPs are not blocked anymore.
