### ISSUE TITLE
OISD NSFW

### ISSUE THREAD

**Issue by peytonjol** [AdguardTeam/HostlistsRegistry#464]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

OISD NSFW

### Blocklist category

Other

### Homepage

https://nsfw.oisd.nl/

### Explanation

i recently purchase adguard dns saas service but i can't find OISD NSFW which was very useful on my local adguardhome system. Thanks !

**Comment by Sergey-Lyapin** [comment]
Hello @peytonjol 
We don't add NSFW lists, because we have built-in parental control.
