### ISSUE TITLE
The Block List Proyect

### ISSUE THREAD

**Issue by HectorRCM** [AdguardTeam/HostlistsRegistry#469]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

The Block List Project

### Blocklist category

Ad blocking, Trackers blocking, Malware&phishing blocking

### Homepage

https://github.com/blocklistproject/Lists

### Explanation

You could consider adding the block list project to the filters especially lists, Ramsomware, Phishing and Tracking. all of very good reputation and constantly updated

**Comment by Sergey-Lyapin** [comment]
Hello @HectorRCM
Thank you for the suggestion.
These lists are not well maintained, for example the ramsomware list was last updated 3 years ago.
