### ISSUE TITLE
Apply HostfilesRegistry to "AdGuard for Windows"' and "AdGuard for Android"'s "DNS Filtering" modes

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/HostlistsRegistry#472]
(None of the 2 issue forms were suited for this.)

I've been puzzled for a couple years now that the [Filters section of HostlistsRegistry](https://github.com/AdguardTeam/HostlistsRegistry/tree/main/filters) have not been applied to the two AdGuard versions in question, despite both of them also having optional *DNS Filtering* modes that are directly comparable to AdGuard Home's syntax support.

Would it be possible to get it in expedited track to implement those lists in the two softwares?

<details><summary>AdGuard for Windows screenshot:</summary>

![image](https://github.com/AdguardTeam/HostlistsRegistry/assets/22780683/5d70c68f-bd79-4dd7-aaf4-a0eefc569c9f)

</details>
<details><summary>AdGuard for Android screenshot:</summary>

![image](https://github.com/AdguardTeam/HostlistsRegistry/assets/22780683/94b62784-ef67-4c96-8d67-8d193a1879e6)

</details>

This issue is somewhat similar to https://github.com/AdguardTeam/AdguardForWindows/issues/4533, except the latter is going slower than I hoped it would. No such issue has been submitted to https://github.com/AdguardTeam/AdguardForAndroid/issues that I can tell.

I don't have the means to test "AdGuard for Mac", as Macs are both too slow and too costly.

**Comment by ameshkov** [comment]
We actually have something like that on the roadmap, but only after we implement a filters management library. It's under development and supposed to be used by all other products.
