### ISSUE TITLE
Please add list "someonewhocares.org Dan Pollock"

### ISSUE THREAD

**Issue by azafrak** [AdguardTeam/HostlistsRegistry#48]
Please add list "someonewhocares.org Dan Pollock"

https://someonewhocares.org/hosts

**Comment by DandelionSprout** [comment]
I get the personal impression that that list is a bit old-fashioned and contains overly old entries (e.g. `goatse.cx`), but there haven't been all that many complaints about the list over the span of some ≥20 years.

**Comment by krystian3w** [comment]
BTW: List is in https://github.com/AdguardTeam/HostlistsRegistry/issues/43

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/HostlistsRegistry/blob/main/filters/general/filter_4_DanPollocksList/filter.txt - these are inactive?

**Comment by ameshkov** [comment]
Yeah, the list receives not many updates. Likely to be removed later.

**Comment by krystian3w** [comment]
I meant added 30-180 days before this issue was made (may have been the fault of the system that passes repository commits to the dns/home interface).
