### ISSUE TITLE
Hagezi block safesearch

### ISSUE THREAD

**Issue by cruxoooo** [AdguardTeam/HostlistsRegistry#481]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

HaGeZi's safesearch not supported DNS Blocklist

### Blocklist category

Other

### Homepage

https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/nosafesearch.txt

### Explanation

Please add "Hagezis safesearch not supported DNS Blocklist" to give users an easy option to block search engines without safesearch.

**Comment by Sergey-Lyapin** [comment]
We decided not to add this list because we think it will not be in demand by users.
