### ISSUE TITLE
Please add Steven Black’s porn only blocklist

### ISSUE THREAD

**Issue by nhlchan** [AdguardTeam/HostlistsRegistry#485]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

Steven Black’s porn only blocker

### Blocklist category

Other

### Homepage

https://github.com/StevenBlack/hosts

### Explanation

This porn blocker is better than the default blocklist in adguard dns ( private and family-protection).Many popular porn websites like xhwide.com doesn’t completely get blocked in default. This blocklist should be in the list. 
link is here : https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn-only/hosts

**Comment by cruxoooo** [comment]
I just checked and the website "xhwide.com" is blocked by the public Family DNS.

**Comment by nhlchan** [comment]
Even if its blocked, my safari shows only the html part of the website. And there are many porn sites i could access with public family
dns.

**Comment by cruxoooo** [comment]
> Even if its blocked, my safari shows only the html part of the website. And there are many porn sites i could access with public family dns. Sent from my iPhone
> […](#)
> On 20 Apr, 2024, at 10:11 AM, cruxoooo ***@***.***> wrote: ﻿ I just checked and the website "xhwide.com" is blocked by the public Family DNS. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.

The .html part shown must be cached by your browser. 
Yes, Family DNS is far from perfect, but you are welcome to report these adult websites to support@adguard.com.

**Comment by nhlchan** [comment]
It doesn’t matter(I opened it on incognito mode). Now just please add the steven blacks anti porn into the list I mentioned.

**Comment by Sergey-Lyapin** [comment]
Hello,
We don't add NSFW lists because we have our own "Block adult websites" option in the parental control.
