### ISSUE TITLE
Add blocklist: Hagezi Multi LIGHT - Basic protection

### ISSUE THREAD

**Issue by tempemafia808** [AdguardTeam/HostlistsRegistry#486]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

Hagezi Multi LIGHT - Basic protection

### Blocklist category

Ad blocking, Trackers blocking

### Homepage

https://github.com/hagezi/dns-blocklists

### Explanation

One of Hagezi's blocklists. This version is similar to Normal version, but better if users want to set-and-forget the configuration.

**Comment by Sergey-Lyapin** [comment]
Hello, 
We have decided not to add this list for now, a Normal version should be enough for "set-and-forget" purposes.
