### ISSUE TITLE
Xiaomi native tracker list

### ISSUE THREAD

**Issue by biomednet** [AdguardTeam/HostlistsRegistry#487]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

Xiaomi native tracker list

### Blocklist category

Trackers blocking

### Homepage

https://github.com/hagezi/dns-blocklists?tab=readme-ov-file#native

### Explanation

Xiaomi is very popular all over the world.
At the same time, Xiaomi devices collect a huge amount of different data.
I suggest adding the ability to connect the blocking list of famous Xiaomi trackers.

Сяоми пользуется огромной популярностью во всем мире.
При этом аппараты сяоми собирают огромное количество различных данных.
Предлагаю добавить возможность подключения списка блокировки известных трекеров Сяоми.

**Comment by hagezi** [comment]
RAW: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/native.xiaomi.txt

Included in Pro++ and Ultimate.

**Comment by biomednet** [comment]
"Included in Pro++ and Ultimate"
Это очень "тяжёлые" списки, и их применение ставить функциональность под вопрос. Особенно учитывая, что моим DNS пользуется несколько друзей. 
Поэтому интересно выделить список в отдельную позицию.
