### ISSUE TITLE
Add HaGeZi's Pop-Up Ads DNS Blocklist

### ISSUE THREAD

**Issue by fynks** [AdguardTeam/HostlistsRegistry#490]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

HaGeZi's Pop-Up Ads DNS Blocklist

### Blocklist category

Ad blocking, Other

### Homepage

https://github.com/hagezi/dns-blocklists?tab=readme-ov-file#popupads

### Explanation

This adds the pop-up ads block list at the dns level and will help remove the popups from websites at network(DNS) level.

**Comment by Sergey-Lyapin** [comment]
Hello @hagezi 
I'm not sure if we should add this list separately. 
Could you tell what percentage of the rules from this filter are included in the Ultimate filter?

**Comment by hagezi** [comment]
@Sergey-Lyapin In the combination of the Pro or higher and additionally the Threat Intelligence Feeds (TIF), all domains from the Pop-Up Ads list are included. This means that if you use the Pro or higher and also the TIF full, you no longer need to add this list separately.

A combination would be useful for users of my Normal or other lists.

**Comment by Sergey-Lyapin** [comment]
Ok, then we won’t add this list separately, thank you.
