### ISSUE TITLE
Add 1Hosts Pro

### ISSUE THREAD

**Issue by GrainStar** [AdguardTeam/HostlistsRegistry#491]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

1Hosts Pro

### Blocklist category

Ad blocking

### Homepage

https://badmojr.github.io/1Hosts/

### Explanation

The blocklist lists 1Hosts Mini /Lite but not Pro, please add it!

**Comment by Sergey-Lyapin** [comment]
This list will be added once [this](https://github.com/AdguardTeam/AdGuardDNS/issues/758) task has been completed.

**Comment by Sergey-Lyapin** [comment]
Duplicate
https://github.com/AdguardTeam/HostlistsRegistry/issues/50
