### ISSUE TITLE
Divested Combined Blocklist

### ISSUE THREAD

**Issue by Retold3202** [AdguardTeam/HostlistsRegistry#492]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

Divested Combined Blocklist

### Blocklist category

Ad blocking, Trackers blocking, Malware&phishing blocking

### Homepage

https://divested.dev/pages/dnsbl

### Explanation

Hey @AdguardTeam, hope this reaches you well.

This is a very comprehensive blocklist maintained by Divested Computing Group (widely trusted and well known for DivestOS, the Mull browser, Hypatia, etc) that blocks ads/trackers/telemetry/malware/etc. It uses a wide variety of sources, including Divested's own lists. 

This list is very effective and has much wider coverage than existing lists here. Contains a lot of domains that others miss. I feel like it'd make an excellent addition to Adguard's blocklists, and would give Adguard an advantage over competitors. 

Hope this will be considered. :)

**Comment by Sergey-Lyapin** [comment]
Hello, @Retold3202 thanks for your suggestion.
According to our [requirements](https://github.com/AdguardTeam/HostlistsRegistry?tab=readme-ov-file#-what-blocklists-can-be-added-here) "if there is a repository on GitHub, the number of stars should be at least 50.".
Repositories related to this list have too few stars:
https://github.com/divestedcg/dnsbl
https://github.com/divestedcg/dnsrm

Btw you can use this list in AdGuard Home:
https://github.com/AdguardTeam/AdGuardHome
