### ISSUE TITLE
Adult Content Blocklist

### ISSUE THREAD

**Issue by virtualvoyager367** [AdguardTeam/HostlistsRegistry#504]
### Prerequisites

- [x] The blocklist is created specifically for DNS-level blockers;
- [x] The blocklist is regularly updated (at least 10 updates per month);
- [x] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

Adult Content Blocklist

### Blocklist category

Other

### Homepage

https://github.com/virtualvoyager367/Adult-Website-Blocklist-for-AdGuard

### I want it to be included for the safety of kids and teenagers.

this blocklist blocks gambling, dating, Explicit Content, and cam websites

this is so all the parents using this can easily keep their kids safe from bad content. the updates on it per month may vary due to not many sites focused on listing these dangerous websites.

this is not popular yet, but I'm hoping to help their lives by keeping them away from addiction and very inappropriate content

**Comment by KnightmareVIIVIIXC** [comment]
Quick question about your list because I'm noticing it more: Is there a reason some of the domains in your list are capitalized?

**Comment by virtualvoyager367** [comment]
I copied and pasted a list of websites from another website and then turned the websites i copied into a blocklist for adguard

________________________________

**Comment by Sergey-Lyapin** [comment]
Hello, @virtualvoyager367. Thanks for your suggestion.

Unfortunately, this list does not meet our [requirements](https://github.com/AdguardTeam/HostlistsRegistry?tab=readme-ov-file#-what-blocklists-can-be-added-here):

- The blocklist should be relatively popular, meaning:
  - if there is a repository on GitHub, the number of stars should be at least 50.
  - if there is no repository on GitHub, the number of reported issues and discussions should be at least 10 per month.
  - the blocklist should be actively supported for at least 6 months.

By the way your list can be used in [AdGuard Home](https://github.com/AdguardTeam/AdGuardHome)

**Comment by virtualvoyager367** [comment]
@Sergey-Lyapin So... it is on there? it's fine if it is not, I will continue to add more and wait for it to meet the requirements if it is not on there, if it is I will still continue to further look for more websites to update it with
