### ISSUE TITLE
Add hBlock

### ISSUE THREAD

**Issue by ParhamzXc** [AdguardTeam/HostlistsRegistry#506]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

hBlock

### Blocklist category

Ad blocking, Trackers blocking, Malware&phishing blocking

### Homepage

https://hblock.molinero.dev/

### Explanation

This guy is a pro in sniffing the correct URL and Ip
Don't know about update rate, but there should be an update in 24 hours for sure
He is accurate
Thanks Ad-Gaurd Team

**Comment by KnightmareVIIVIIXC** [comment]
https://github.com/AdguardTeam/HostlistsRegistry#what-blocklists

**Comment by Sergey-Lyapin** [comment]
Hello @ParhamzXc, thanks for the suggestion.
This list is a compilation, and we prefer original lists to compilations.
We recommend using Adguard DNS filter or other available lists for instance HaGeZi's Pro++ Blocklist.

**Comment by ParhamzXc** [comment]
right, ty
