### ISSUE TITLE
HaGeZi's Windows/Office Tracker Blocklist

### ISSUE THREAD

**Issue by hagezi** [AdguardTeam/HostlistsRegistry#507]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

HaGeZi's Windows/Office Tracker Blocklist

### Blocklist category

Other

### Homepage

https://github.com/hagezi/dns-blocklists

### Explanation

Blocks Windows/Office/MSN/Bing native broadband tracker that track your activity.

RAW-Link: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/native.winoffice.txt

As a replacement for the no longer maintained list `WindowsSpyBlocker - Hosts spy rules`
I have extended my list to cover the "old" list, apart from the false positives, off-topic domains and dead domains.
Related: https://github.com/AdguardTeam/HostlistsRegistry/issues/452

**Comment by KnightmareVIIVIIXC** [comment]
Is the Windows/Office Tracker list in the Ultimate List?

**Comment by Hell0Earth** [comment]
Still waiting for this list 😔

**Comment by Sergey-Lyapin** [comment]
Added
