### ISSUE TITLE
Cookie Notices

### ISSUE THREAD

**Issue by carizma019** [AdguardTeam/HostlistsRegistry#509]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

Cookie Notices

### Blocklist category

Trackers blocking

### Homepage

https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_18_Annoyances_Cookies/filter.txt

### Explanation

blocks cookie notices on web pages

**Comment by hagezi** [comment]
Network-wide blocking of CMPs (Consent Management Plattform/Provider) used for cookie consent solutions breaks a lot of things and takes away the user's freedom to decide what he wants to allow and what not - blocking usually allows everything ([#1979](https://github.com/hagezi/dns-blocklists/issues/1979#issuecomment-1870498567)).

Blocking or automatic allow/deny is reserved for content blockers with corresponding filter lists. These can be used to decide which sites are excluded from blocking a specific CMP domain and which are not. You only have to look at the exclusions in the known cookie filter lists to see why network wide blocking via DNS is not a good idea.
