### ISSUE TITLE
Please add EasyPrivacy 

### ISSUE THREAD

**Issue by wengkitttt** [AdguardTeam/HostlistsRegistry#511]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

EasyPrivacy

### Blocklist category

Trackers blocking

### Homepage

https://firebog.net/

### Explanation

My first reason for this request is that currently, all the blocklists in AdGuard DNS block both trackers and ads. There is no single blocklist that blocks trackers only. Therefore, I would like to request a blocklist that specifically targets trackers.

The second reason is that ads are a significant, if not the only, source of revenue for most websites, supporting content creators. This blocklist provides a balanced approach, safeguarding privacy while still supporting online content.

Lastly, by including this tracker-only blocklist, users will have the option to decide whether to block trackers only or both ads and trackers.

EasyPrivacy is an optional supplementary filter list that completely removes all forms of tracking from the internet, including web bugs, tracking scripts, and information collectors, thereby protecting our personal data.

https://v.firebog.net/hosts/Easyprivacy.txt

**Comment by wengkitttt** [comment]
This is the original URL to the blocklist: https://easylist.to/easylist/easyprivacy.txt. However, I'm not sure if the syntax is compatible with AdGuard DNS.

Please consider which URL has the syntax that would work best for AdGuard DNS.

**Comment by Sergey-Lyapin** [comment]
Hello @wengkitttt
EasyPrivacy is designed for use in content blockers and is already available in AdGuard adblocker apps and extensions.

Tracking domains from EasyPrivacy is already [included](https://github.com/AdguardTeam/AdGuardSDNSFilter?tab=readme-ov-file#tracking-servers) in AdGuard DNS blocklist.
