### ISSUE TITLE
Add Ukraine Region-specific DNS blocklist please!

### ISSUE THREAD

**Issue by dgzargo** [AdguardTeam/HostlistsRegistry#515]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

Ukraine Region-specific DNS blocklist

### Blocklist category

Ad blocking, Trackers blocking, Malware&phishing blocking, Other

### Homepage

https://github.com/basilalex/blocklists

### Explanation

It's a blocker that satisfies the need of the whole region.

- 18+
- Abuse
- Dating / Dating agencies
- Illegal medicines
- Fraud
- Gambling
- Malware / Ransomware / Piracy
- Phishing / Scam
- Ads / Tracking / Privacy / Analytics
- Smoking / Vaping / Hookahs

**Comment by dgzargo** [comment]
![image](https://github.com/user-attachments/assets/5342c0d2-c680-46e3-98a9-019d00992a94)
That's the effectiveness of DNS filters + AdGuard Adblocker now.

**Comment by dgzargo** [comment]
![image](https://github.com/user-attachments/assets/c899b78d-8a70-4ea4-8b18-9e851889acd1)
And this is MS Edge without AdGuard Adblocker

**Comment by Sergey-Lyapin** [comment]
Hello @dgzargo
These lists do not meet the [requirements](https://github.com/AdguardTeam/HostlistsRegistry?tab=readme-ov-file#-what-blocklists-can-be-added-here):
- The blocklist should be relatively popular, meaning:
  - if there is a repository on GitHub, the number of stars should be at least 50.
  - if there is no repository on GitHub, the number of reported issues and discussions should be at least 10 per month.
  - the blocklist should be actively supported for at least 6 months.
- The blocklist should be regularly updated with at least 10 updates per month.

What test do you use to check effectiveness?

**Comment by Alex-302** [comment]
@Sergey-Lyapin https://d3ward.github.io/toolz/adblock.html it is.

My result with the Default AdGuard server

<details>
<summary>Details</summary>

![image](https://github.com/user-attachments/assets/72b02ff4-e677-46dc-9644-5bf8919ca6df)


</details>

This test is bad, because it also checks domains which are not used for ads/tracking.
