### ISSUE TITLE
Streaming apps

### ISSUE THREAD

**Issue by cassu123** [AdguardTeam/HostlistsRegistry#516]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [x] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

Streaming App Blocklist

### Blocklist category

Ad blocking

### Homepage

N/a

### Explanation

I use Google Chromecast TV with Adguard.   Some software such as Hulu have embedded ads that get around Adguard. Im requesting a Blocklist that will help cut down the 2 minutes of ads. I also do not know what the homepage website is

**Comment by Sergey-Lyapin** [comment]
Hello @cassu123
Unfortunately ads on Hulu cannot be blocked by DNS filtering.
