### ISSUE TITLE
Can you add Arabic Liste blocklist? (Liste AR HOSTS)

### ISSUE THREAD

**Issue by bigplayer-ai** [AdguardTeam/HostlistsRegistry#519]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

Liste AR HOSTS

### Blocklist category

Ad blocking, Trackers blocking, Malware&phishing blocking

### Homepage

https://raw.githubusercontent.com/easylist/listear/master/hosts.txt

### Explanation

https://raw.githubusercontent.com/easylist/listear/master/hosts.txt

it is arabic specific dns filter list...

**Comment by Sergey-Lyapin** [comment]
Hello @bigplayer-ai
This list does not meet the [requirements](https://github.com/AdguardTeam/HostlistsRegistry?tab=readme-ov-file#-what-blocklists-can-be-added-here):
```
- The blocklist should be relatively popular, meaning:
  - if there is a repository on GitHub, the number of stars should be at least 50.
  - if there is no repository on GitHub, the number of reported issues and discussions should be at least 10 per month.
  - the blocklist should be actively supported for at least 6 months.
- The blocklist should be regularly updated with at least 10 updates per month.
```

**Comment by bigplayer-ai** [comment]
> Hello @bigplayer-ai This list does not meet the [requirements](https://github.com/AdguardTeam/HostlistsRegistry?tab=readme-ov-file#-what-blocklists-can-be-added-here):
> 
> ```
> - The blocklist should be relatively popular, meaning:
>   - if there is a repository on GitHub, the number of stars should be at least 50.
>   - if there is no repository on GitHub, the number of reported issues and discussions should be at least 10 per month.
>   - the blocklist should be actively supported for at least 6 months.
> - The blocklist should be regularly updated with at least 10 updates per month.
> ```

ok it does not meet the requirement but this is regional specific language list, you should add this IMO...
