### ISSUE TITLE
Add Newly Registered Domains (NRDs) 14-Day List

### ISSUE THREAD

**Issue by agranapz** [AdguardTeam/HostlistsRegistry#523]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

Newly Registered Domains (NRDs) 14-Day List

### Blocklist category

Ad blocking

### Homepage

https://github.com/xRuffKez/NRD

### Explanation

This repository contains NRD (Newly Registered Domains) lists for various adblockers and DNS filtering solutions. The lists are provided in multiple formats to support different tools and applications. These lists help enhance privacy and reduce unwanted traffic by blocking newly registered domains that are often associated with advertisements, trackers, and other unwanted content. It also prevents new threats, because NRD are favored by black hats.

https://raw.githubusercontent.com/xRuffKez/NRD/main/nrd-14day_adblock.txt

**Comment by agranapz** [comment]
That list is for 14 days

**Comment by Alex-302** [comment]
@agranapz 14 days may be annoying for users. But you may open a feature request about choice of 
a period of NRD

https://github.com/AdguardTeam/AdGuardDNS
