### ISSUE TITLE
Feature request: Adding custom blocklists by user

### ISSUE THREAD

**Issue by KianiDev** [AdguardTeam/HostlistsRegistry#525]
This is a feature that I want it. Instead of opening requests on GitHub for adding blocklists, allow the user to import any blocklist with a link.

For example, I want to add 1Hosts Pro to my DNS server blocklists. Instead of posting it here and waiting for it to get added, add it to the blocklists.

To prevent adding very big blocklists to overload the server put a limit.

Thanks!

(This is for AdGuard DNS; other AdGuard apps have this feature.)

**Comment by Sergey-Lyapin** [comment]
Hello @KianiDev
The possibility of adding such a feature will be considered here:
https://github.com/AdguardTeam/AdGuardDNS/issues/836
