### ISSUE TITLE
4OD TV Advert Blocklist (UK TV)

### ISSUE THREAD

**Issue by bragg2012** [AdguardTeam/HostlistsRegistry#53]
Please can this 4OD blocklist be added - removes ads on the channel4/4OD apps in the UK for on-demand content.

**Raw blocklist:**
https://gist.githubusercontent.com/jcass8695/d766fd65c0240b5c424ed73b17664db6/raw/47c2cf65951fca1d8c913cbd672f9ddab52d84d6/4od-blocklist.txt

**Github**
https://gist.github.com/jcass8695/d766fd65c0240b5c424ed73b17664db6

**Comment by DandelionSprout** [comment]
Seems like there could actually be grounds to add those domains to AdGuard Base or EasyList (thus most likely ensuring they're also used in AdGuard DNS Filter), a possibility that I'd personally prefer compared to adding a 9-entry list with no metadata.

**Comment by ameshkov** [comment]
Does not satisfy the repo rules:
https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here
