### ISSUE TITLE
Germany (Kleinanzeigen.de)

### ISSUE THREAD

**Issue by ckdiak** [AdguardTeam/HostlistsRegistry#536]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

easylistgermany+easylist.txt

### Blocklist category

Ad blocking

### Homepage

https://easylist-downloads.adblockplus.org/easylistgermany+easylist.txt

### Explanation

<img width="1440" alt="Screenshot 2024-09-17 at 02 41 44" src="https://github.com/user-attachments/assets/db0f66ef-d56e-45b5-aca2-89eec9d7f0e0">

**Comment by Sergey-Lyapin** [comment]
Hello @ckdiak

The list provided is designed for use in content blockers, this repo is for DNS-oriented blocklists.
Domains from EasyList and Easylist Germany is already [included](https://github.com/AdguardTeam/AdGuardSDNSFilter?tab=readme-ov-file#ad-servers) in AdGuard DNS blocklist.

**Comment by ckdiak** [comment]
It does not block ads on Kleinanzeigen.

**Comment by hagezi** [comment]
@ckdiak Yes, because the ads can only be blocked with a content blocker, not via DNS.
