### ISSUE TITLE
Ukrainian Security Filter - request to add

### ISSUE THREAD

**Issue by RossBogdanov** [AdguardTeam/HostlistsRegistry#537]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

Ukrainian Security Filter

### Blocklist category

Ad blocking, Trackers blocking, Malware&phishing blocking

### Homepage

https://github.com/braveinnovators/ukrainian-security-filter

### Explanation

Please add "Ukrainian Security Filter" to give users an easy option to block phishing, threats; improving security and privacy. 
Thank You in advance.

**Comment by Sergey-Lyapin** [comment]
Added
