### ISSUE TITLE
HaGeZi's Samsung Tracker Blocklist

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/HostlistsRegistry#538]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

HaGeZi's Samsung Tracker Blocklist

### Blocklist category

Other

### Homepage

https://github.com/hagezi/dns-blocklists

### Explanation

Blocks Samsung native broadband tracker that track your activity.
Source RAW URL:  `https://raw.githubusercontent.com/hagezi/dns-blocklists/refs/heads/main/adblock/native.samsung.txt`

CC @hagezi

**Comment by Sergey-Lyapin** [comment]
Added
