### ISSUE TITLE
Allow us to specify a URL to our own custom blocklist

### ISSUE THREAD

**Issue by jaypatrick** [AdguardTeam/HostlistsRegistry#539]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

Our own custom blocklist

### Blocklist category

Ad blocking

### Homepage

https://example.com

### Explanation

Why can't we specify our own blocklists like we can in the various clients, AdGuard Home, etc? In the apps, we can specify our own custom blocklist. Otherwise, I have to keep up with half a dozen custom rule sets on adguard dns servers to keep them synched up with my custom list in github.

**Comment by Sergey-Lyapin** [comment]
Hello @jaypatrick

I [recreated](https://github.com/AdguardTeam/AdGuardDNS/issues/836) the issue in AdGuardDNS repo.
