### ISSUE TITLE
Please add adblock-nocoin-list

### ISSUE THREAD

**Issue by honeyandbadger** [AdguardTeam/HostlistsRegistry#542]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [ ] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

adblock-nocoin-list

### Blocklist category

Other

### Homepage

https://github.com/hoshsadiq/adblock-nocoin-list

### Explanation

This is good one. It blocks cryptomining over browser session. Webpages slow down if they have cryptomining. They take up too much local resources to mine crypto on your own device.

**Comment by Sergey-Lyapin** [comment]
Hello @honeyandbadger
We already have this list.
![Blocklist](https://github.com/user-attachments/assets/95a73936-0b91-485b-93c8-964af47b02ea)
