### ISSUE TITLE
IndianList (request for blocklist)

### ISSUE THREAD

**Issue by honeyandbadger** [AdguardTeam/HostlistsRegistry#543]
### Prerequisites

- [ ] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

IndianList

### Blocklist category

Ad blocking

### Homepage

https://github.com/mediumkreation/IndianList

### Explanation

IndianList is also an amazing blocklist. Used in Brave https://community.brave.com/t/indian-list-source/548272
Thank you.

**Comment by Sergey-Lyapin** [comment]
Hello @honeyandbadger
IndianList is designed for use in content blockers and is already [available](https://github.com/AdguardTeam/FiltersRegistry/tree/master/filters/ThirdParty/filter_253_IndianList) in AdGuard adblocker apps and extensions.
This repo is for DNS-oriented blocklists.

**Comment by androidghosh** [comment]
> Hello @honeyandbadger IndianList is designed for use in content blockers and is already [available](https://github.com/AdguardTeam/FiltersRegistry/tree/master/filters/ThirdParty/filter_253_IndianList) in AdGuard adblocker apps and extensions. This repo is for DNS-oriented blocklists.

Is this list incompatible with DNS-oriented blocklists ? Why not add this if it is compatible?
