### ISSUE TITLE
Add blocklists

### ISSUE THREAD

**Issue by curability4apish** [AdguardTeam/HostlistsRegistry#544]
I suggest adding the following blacklists: 1Hosts Pro, HBLOCK and several popular blocklists which RethinkDNS uses.

**Comment by Sergey-Lyapin** [comment]
Hello @curability4apish, thanks for the suggestion.
HBLOCK is a compilation, and we prefer original lists to compilations.
We recommend using Adguard DNS filter or other available lists for instance HaGeZi's Pro++ Blocklist.

As for 1Hosts Pro, to add this list, we need to implement [additional functionality](https://github.com/AdguardTeam/AdGuardDNS/issues/758) in the application, we will add this list in the future.

**Comment by curability4apish** [comment]
The additional features are redundant. It is well known that some filters are trades of privacy for functionality, but it's not necessarily that they are dangerous or useless to anyone -- This is why the whitelist is made for.

**Comment by curability4apish** [comment]
Switched to RethinkDNS
