### ISSUE TITLE
1hosts (Pro)

### ISSUE THREAD

**Issue by MrDannyD** [AdguardTeam/HostlistsRegistry#559]
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

1hosts (Pro)

### Blocklist category

Ad blocking, Trackers blocking, Malware&phishing blocking

### Homepage

https://github.com/badmojr/1Hosts/tree/master/Pro

### Explanation

World's most advanced DNS filter-/blocklists! 
Pro Version: strict; has some minimal breakages, prioritizes privacy & safety (adblocking) over UX e.g blocks graph.facebook.com.

**Comment by Alex-302** [comment]
Duplicate of https://github.com/AdguardTeam/HostlistsRegistry/issues/50

Waiting for https://github.com/AdguardTeam/AdGuardDNS/issues/758
