### ISSUE TITLE
Appwrite cloud is being blocked

### ISSUE THREAD

**Issue by DH-555** [AdguardTeam/HostlistsRegistry#560]
Appwrite cloud Backend As A Service (BaaS) like Firebase or Supabase is being blocked by this blocklist and listed as malicious, affecting thousands of projects using this tool.

What's appwrite?
https://appwrite.io
https://github.com/appwrite/appwrite

Blocked domain:
https://cloud.appwrite.io

**Comment by Alex-302** [comment]
Which filter blocks it?
