### ISSUE TITLE
PersianBlocker list for Persian websites

### ISSUE THREAD

**Issue by MasterKia** [AdguardTeam/HostlistsRegistry#59]
https://github.com/AdguardTeam/FiltersRegistry/issues/617

[PersianBlocker](https://raw.githubusercontent.com/MasterKia/PersianBlocker/main/PersianBlocker.txt) is currently available in uBlock Origin and AdGuard extensions.

I'm in contact with @DRSDavidSoft and therefore I've fully combined the [Unwanted-Iranian](https://github.com/DRSDavidSoft/additional-hosts/blob/master/domains/blacklist/unwanted-iranian.txt) list from @DRSDavidSoft into the PersianBlocker list and created a list suitable for DNS-level blockers, PersianBlockerHosts:
https://raw.githubusercontent.com/MasterKia/PersianBlocker/main/PersianBlockerHosts.txt

Unwanted-Iranian is currently [a part of AdGuard Home](https://github.com/AdguardTeam/HostlistsRegistry/blob/main/filters/regional/filter_19_IRN_UnwantedIranianDomains/filter.txt) but it has some dead links, so the PersianBlockerHosts list (or you could use the name "PersianBlocker (Hosts)") could either replace it or be added alongside it.

**Comment by MasterKia** [comment]
I changed the list name from PersianPiHole into "PersianBlockerHosts".
"PersianBlocker (Hosts)" is fine with me as well.

https://raw.githubusercontent.com/MasterKia/PersianBlocker/main/PersianBlockerHosts.txt

**Comment by ameshkov** [comment]
I reckon we should replace "Unwanted Iranian" list with yours then since it's a combination.
