### ISSUE TITLE
block list suggestions

### ISSUE THREAD

**Issue by Mile-Lile** [AdguardTeam/HostlistsRegistry#60]
[StevenBlack](https://github.com/StevenBlack/hosts)

[notracking](https://github.com/notracking/hosts-blocklists)

[AdAway](https://github.com/AdAway/adaway.github.io)

[crazy-max](https://github.com/crazy-max/WindowsSpyBlocker)

[lightswitch05](https://github.com/lightswitch05/hosts)

[no-google](https://github.com/nickspaargaren/no-google)

**Comment by ameshkov** [comment]
Duplicates already opened issues.
