### ISSUE TITLE
Pleased add OISD NSFW List and AdGuard Filters

### ISSUE THREAD

**Issue by dontobi** [AdguardTeam/HostlistsRegistry#63]
https://abp.oisd.nl/nsfw/

https://kb.adguard.com/en/general/adguard-ad-filters

**Comment by AidanGee7** [comment]
+1 

The built in "Parental control" option of AdGuard DNS doesn't seem to have as much NSFW blocking as OISD does.

**Comment by ameshkov** [comment]
We would like to avoid adding additional NSFW blocking lists as this should be covered by the Parental control feature.

If it currently does not catch some domains that other lists do, we will improve this, just let us know about it:)
