### ISSUE TITLE
Add CoinBlockerLists

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/HostlistsRegistry#64]
Yes, the lists are still actively maintained @ https://gitlab.com/ZeroDot1/CoinBlockerLists & subscribable @ https://zerodot1.gitlab.io/CoinBlockerListsWeb/downloads.html, but still not yet added to any section of AG subscriptions.

_Originally posted by @TPS in https://github.com/AdguardTeam/FiltersRegistry/issues/56#issuecomment-1190801593_

**Comment by FadeMind** [comment]
@zloyden `404` error. Seems EOL

**Comment by Alex-302** [comment]
It seems it is alive.

**Comment by Sergey-Lyapin** [comment]
`The blocklist should be regularly updated with at least 10 updates per month.`

[Last modified: 2023-06-17 07:43:01](https://gitlab.com/ZeroDot1/CoinBlockerLists/-/commit/9a8988c3ebe35876778c175ac527bf1752737a3c)
https://gitlab.com/ZeroDot1/CoinBlockerLists/-/blob/master/hosts

It seems like this list is not updated often enough.

**Comment by Alex-302** [comment]
The actuality of such filters is low now, as the boom of mining (including malicious) has gone.
