### ISSUE TITLE
Add all Energized Protection and 1Hosts filters

### ISSUE THREAD

**Issue by Ddarkover** [AdguardTeam/HostlistsRegistry#65]
You can add all Energized Protection and 1Hosts filters.
And add RUAdList to the regional filters.

**Comment by amarodeabreu** [comment]
https://block.energized.pro/unified/formats/filter

Please add these filters

**Comment by krystian3w** [comment]
Ru Adlist is disabled: https://github.com/AdguardTeam/FiltersRegistry/pull/507
