### ISSUE TITLE
[Filter Request] List of DNS blocks list for best UX

### ISSUE THREAD

**Issue by dalisoft** [AdguardTeam/HostlistsRegistry#72]
## List of popular blockers

If these list can be enabled in Settings, this can give user 98% privacy and 99% ad-blocking results, even for TV's. Tested by me (@dalisoft)

- [ ] goodbye-ads (https://github.com/jerryn70/GoodbyeAds)
- [x] steven-black (https://github.com/StevenBlack/hosts)
- [x] adaway (https://github.com/AdAway/adaway.github.io)
- [x] adguard-dns-filter (https://github.com/AdguardTeam/AdguardSDNSFilter)
- [ ] uncheckyads (https://github.com/FadeMind/hosts.extras/tree/master/UncheckyAds)
- [ ] someonewhocares (https://someonewhocares.org/hosts/)
- [ ] adguard-tracking-protection-filter (https://kb.adguard.com/en/general/adguard-ad-filters#tracking-protection-filter)
- [ ] r-a-y-mobile-hosts (https://github.com/r-a-y/mobile-hosts)
- [ ] easyprivacy (https://easylist.to)
- [ ] easylist (https://easylist.to)
- [ ] 1hosts-pro (https://github.com/badmojr/1Hosts) **Currently Lite version**
- [x] peter-lowe (https://pgl.yoyo.org/as/index.php)
- [ ] energized-ultimate (https://github.com/EnergizedProtection/block) **Currently Spark version**
- [ ] energized-ips (https://github.com/EnergizedProtection/block)
- [x] windowsspyblocker-spy (https://github.com/crazy-max/WindowsSpyBlocker)
- [x] oisd (https://oisd.nl)
- [x] notracking (https://github.com/notracking/hosts-blocklists)
- [x] perflyst-smarttv (https://github.com/Perflyst/PiHoleBlocklist)
- [ ] adguard-russian-filter (https://kb.adguard.com/general/adguard-ad-filters#russian-filter)
- [ ] ru-adlist (https://forums.lanik.us/viewforum.php?f=102)

**Comment by ameshkov** [comment]
Oh, it's much better to file an issue per list.

A few comments on what's reported:

> adguard-tracking-protection-filter
> easyprivacy
> easylist
> adguard-russian-filter
> ru-adlist

These are not DNS blocklists and they should not be used that way.

What's safe for use on the DNS level is already included in AdGuard DNS filter.

> energized-ultimate
> energized-ips

Even Spark is problematic and mostly unmaintained. Adding a bunch of bigger unmaintained lists is not safe.

**Comment by dalisoft** [comment]
@ameshkov After tuning months i'm finally got desired and expected result (maybe a better?), so there is a my new favorite and less bloated DNS servers list

- AdAway Default Blocklist
- Peter Lowe's Blocklist
- 1Hosts (Lite)
- Dan Pollock's List
- Energized Spark
- The NoTracking blocklist (one of best list)
- OISD Blocklist Full (one of best list knew after using AdGuard DNS)
- Steven Black's List
- Phishing URL Blocklist (one of best and well maintained)
- Dandelion Sprout's Anti-Malware
- NoCoin Filter List (one of best)
- Scam Blocklist
- Salkerware Indicators List
- The Big List of Hacked Malware
- Malicious URL Blocklist (the one i'm recommend for safety)
- Dandelion Sprout's Game Console (if you have PS/Xbox)
- Perflyst and Dandelion Sprout

@ameshkov If you any recommendation related to this, i will be thankful, as for now, AdGuard is one of best
