### ISSUE TITLE
GoodbyeAds and Energized Ultimate

### ISSUE THREAD

**Issue by Vucko130** [AdguardTeam/HostlistsRegistry#75]
Please add GoodbyeAds and Energized Ultimate filter

GoodbyeAds: https://github.com/jerryn70/GoodbyeAds
Energized Ultimate: https://github.com/EnergizedProtection/block/tree/master/ultimate

**Comment by ameshkov** [comment]
GoodbyeAds is poorly supported, it does not satisfy the repo rules. https://github.com/AdguardTeam/HostlistsRegistry/issues/73#issuecomment-1337681155

Energized Ultimate is the same, the false positives are there for years.
