### ISSUE TITLE
OISD EXTRA addition

### ISSUE THREAD

**Issue by MaximUSNG** [AdguardTeam/HostlistsRegistry#78]
Hello. You already have the OISD basic and full lists added. But there's still "extra" in addition to these. Available via direct link https://oisd.nl/downloadsXtra
https://abp.oisd.nl/extra
FULL+EXTRA block almost everything

**Comment by badmojr** [comment]
-1

**Comment by ameshkov** [comment]
We'll consider it later when AdGuard DNS UI can properly indicate that the blocklist can cause breakage and there're consequences of using it.

**Comment by jslawler** [comment]
This blocklist no longer exists, and has been replaced by oisd big and oisd small.
