### ISSUE TITLE
please add German AdGuard list

### ISSUE THREAD

**Issue by derKief** [AdguardTeam/HostlistsRegistry#80]
Would be nice if the german AdGuard list could be added.
I found it on https://kb.adguard.com/en/general/adguard-ad-filters

I Guess it should be this one:
https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_6_German/filter.txt

Thanks in advance.

**Comment by ameshkov** [comment]
Hi, it's already included in AdGuard DNS filter so no need to add duplicates.
