### ISSUE TITLE
Add blocklist project lists

### ISSUE THREAD

**Issue by mayankmetha** [AdguardTeam/HostlistsRegistry#82]
https://github.com/blocklistproject/Lists

**Comment by ameshkov** [comment]
There were no updates from Sep 27, 2022 until Dec 2, 2022. Is this blocklist actually maintained well?

Keeping this request open for now, we'll get back to this later.

**Comment by Sergey-Lyapin** [comment]
This list seems to have been maintained well for the last two months.
