### ISSUE TITLE
Please add

### ISSUE THREAD

**Issue by dewittinfl** [AdguardTeam/HostlistsRegistry#83]
https://easylist.to/

This helps to remove gray frames where ads are blocked. Extremely helpful.

**Comment by ameshkov** [comment]
This kind of lists are not compatible with DNS-level blocking

**Comment by dewittinfl** [comment]
But NextDNS can do it?See Screen shot.Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Andrey Meshkov ***@***.***> Date: 9/26/22  10:03 AM  (GMT-05:00) To: AdguardTeam/HostlistsRegistry ***@***.***> Cc: dewittinfl ***@***.***>, Author ***@***.***> Subject: Re: [AdguardTeam/HostlistsRegistry] Please add (Issue #83) 
This kind of lists are not compatible with DNS-level blocking

**Comment by ameshkov** [comment]
They prefer to add everything people bring to them regardless of whether this makes sense or not.
