### ISSUE TITLE
Please add this Youtube ads blocklist Ewpratten/youtube_ad_blocklist

### ISSUE THREAD

**Issue by OdiJordan** [AdguardTeam/HostlistsRegistry#87]
can you please add this youtube block list: https://github.com/Ewpratten/youtube_ad_blocklist

**Comment by UnicornVariant** [comment]
Seconding this request. Right now none of the blocking lists actually block Youtube ads. The list is thorough and should work on all systems including game consoles and mobile devices.

**Comment by ameshkov** [comment]
Cannot add it. The list didn't receive any updates since April and the repo is now archived.
