### ISSUE TITLE
Please add Cert.pl, and KAD - the Polish lists of dangerous  sites.

### ISSUE THREAD

**Issue by lukg20** [AdguardTeam/HostlistsRegistry#88]
1. https://hole.cert.pl/domains/domains_adblock.txt
is the Polish cyber protection agency. Please select the correct filters.

2. https://raw.githubusercontent.com/FiltersHeroes/KAD/master/KAD.txt
A site that saved my family from phishing more than once. There are the most up-to-date lists of really dangerous Polish sites.

--------------------------------------------------------------------------------------------------
sources:
https://cert.pl/en/posts/2020/03/malicious_domains/
https://kadantiscam.netlify.app/

**Comment by lukg20** [comment]
Is there anything going on in this topic?

**Comment by krystian3w** [comment]
#39
