### ISSUE TITLE
Add AI generated Quantum Lists

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/HostlistsRegistry#89]
Please Add the AI generated Quantum Lists : https://gitlab.com/The_Quantum_Alpha/the-quantum-ad-list/-/raw/master/For%20hosts%20file/The_Quantum_Ad-List.txt

Their gitlab : https://gitlab.com/The_Quantum_Alpha/the-quantum-ad-list

**Comment by ameshkov** [comment]
Interesting, but there are not much activity. We'll keep this open and get back to it in a couple months to see how it changed.

**Comment by Alex-302** [comment]
Not sure about it. Mining pools blocked in this filter.
It would be better to have a list to lock them in a separate file. Also it is large - ~120 MB.
@ameshkov Is it acceptable for our DNS?

**Comment by BirdInFire** [comment]
> Not sure about it. Mining pools blocked in this filter.
> It would be better to have a list to lock them in a separate file. Also it is large - ~120 MB.
> @ameshkov Is it acceptable for our DNS?

Since it's been so much time I can't talk about them anymore since I do not actively follow them, if you don't see the point don't hesitate to close the issue.
