### ISSUE TITLE
List of Polish phishing sites (cert.pl)

### ISSUE THREAD

**Issue by goofas** [AdguardTeam/HostlistsRegistry#91]
Please add 
https://hole.cert.pl/domains/domains.txt
it's list of domains with phishing sites send by users by https://incydent.cert.pl/

**Comment by klisza1993** [comment]
yeap. very missing ;)

**Comment by ameshkov** [comment]
Could you please provide the following info:

1. Title
2. Description
3. Homepage

**Comment by goofas** [comment]
> Could you please provide the following info:
> 
> 1. CERT Polska List of malicious domains
> 2 PL: 
CERT Polska zajmuje się incydentami mającymi swoje źródło, bądź których celem są hosty w domenie .pl albo podłączone do NASK lub innego polskiego dostawcy Internetu. Każdy udokumentowany przypadek nadużycia Internetu jest przez nas traktowany z należytą powagą. W szczególności zajmujemy się przypadkami:

wyłudzeń w Internecie,
złośliwego oprogramowania,
ataków typu DoS (Denial of Service) i DDoS (Distributed Denial of Service),
włamań i prób włamania.

2 EN:

CERT Polska deals with incidents and threats originating or aiming at systems in the .pl domain or connected to NASK's or other Polish Internet provider's network. Every documented attempt of Internet abuse is taken very seriously. Specifically, we handle the following types of incidents:

port scans,
spam going through Polish servers,
DoS and DDoS attacks,
break-ins and hacks.

> 3. https://cert.pl/posts/2020/03/ostrzezenia_phishing/

4. List link https://hole.cert.pl/domains/domains.txt

**Comment by Sergey-Lyapin** [comment]
Hello @goofas

The description is too long, let's cut it down to one sentence.

**Comment by Sergey-Lyapin** [comment]
Regarding requirements:
```
- The blocklist should be relatively popular, meaning:
  - if there is a repository on GitHub, the number of stars should be at least 50.
  - if there is no repository on GitHub, the number of reported issues and discussions should be at least 10 per month.
  - the blocklist should be actively supported for at least 6 months.
- The blocklist should be regularly updated with at least 10 updates per month.
```
Is there any way to know if these requirements are satisfied? How long has this list been maintained and how actively?
