### ISSUE TITLE
hagezi/dns-blocklists

### ISSUE THREAD

**Issue by merj1928** [AdguardTeam/HostlistsRegistry#95]
Could they include these blocklists to their DNS service, are maintained regularly and are effective !!!

https://github.com/hagezi/dns-blocklists

**Comment by hagezi** [comment]
Thanks for the idea to integrate my blocklists into AdGuardDNS. That would be great!

My recommendation would be to include the Pro and Pro+ .

https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/pro.txt
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/pro.plus.txt

Thanks and greetings,
Gerd - https://github.com/hagezi/dns-blocklists

**Comment by hagezi** [comment]
https://github.com/AdguardTeam/HostlistsRegistry/pull/101

**Comment by gyCfjSnO** [comment]
I also back adding HaGeZi into AdGuard home, I think they run a REALLY GOOD block list collection!!

**Comment by xopez** [comment]
I have also tested it and it seems similiar to oisd. Really rare false positives. I would appreciate adding this.

**Comment by ameshkov** [comment]
Added, will be switched to `prod` environment later this week.
