### ISSUE TITLE
was energized ultimate not added for a specific reason 

### ISSUE THREAD

**Issue by yeoldehacker** [AdguardTeam/HostlistsRegistry#96]

**Comment by SiddharthSharma16923** [comment]
i mean , yes it has 'some' false positives, but still , its a big compile , why left it out?

**Comment by Dynasty-Dev** [comment]
Some is an understatement and I believe the owner no longer maintains it.

**Comment by ameshkov** [comment]
Right, it's not maintained, does not satisfy the repo rules.
